export interface SeedCard {
  readonly front: string
  readonly back: string
}

// 1000 most common words in Vietnamese (Vietnamese front, English back)
export const VIETNAMESE_SEED_CARDS: SeedCard[] = [
  // Pronouns & forms of address
  { front: 'tôi', back: 'I, me (first person)' },
  { front: 'bạn', back: 'you (friend/peer); friend' },
  { front: 'anh', back: 'older brother; he/you (older male)' },
  { front: 'chị', back: 'older sister; she/you (older female)' },
  { front: 'em', back: 'younger sibling; I (younger speaker)' },
  { front: 'ông', back: 'grandfather; Mr.; he (elderly/respected male)' },
  { front: 'bà', back: 'grandmother; Mrs.; she (elderly/respected female)' },
  { front: 'cô', back: 'aunt; Miss; she (young woman)' },
  { front: 'chú', back: 'uncle; he (middle-aged man)' },
  { front: 'họ', back: 'they, them' },
  { front: 'chúng tôi', back: 'we, us (exclusive — not including listener)' },
  { front: 'chúng ta', back: 'we, us (inclusive — including listener)' },
  { front: 'mình', back: 'myself; we (informal inclusive)' },
  { front: 'nó', back: 'it; he/she (informal)' },
  { front: 'người ta', back: 'people; one; they (impersonal)' },

  // Affirmatives, negatives, basic particles
  { front: 'vâng', back: 'yes (respectful, Northern Vietnamese)' },
  { front: 'dạ', back: 'yes (respectful, Southern Vietnamese/formal)' },
  { front: 'ừ', back: 'yeah; uh-huh (informal agreement)' },
  { front: 'không', back: 'no; not' },
  { front: 'có', back: 'yes; to have; there is/are' },
  { front: 'được', back: 'okay; can; allowed; achieved' },
  { front: 'rồi', back: 'already; then; done; okay' },
  { front: 'thôi', back: 'enough; stop; let\'s not; okay then' },

  // Greetings & common expressions
  { front: 'xin chào', back: 'hello; greetings' },
  { front: 'tạm biệt', back: 'goodbye; farewell' },
  { front: 'cảm ơn', back: 'thank you' },
  { front: 'xin lỗi', back: 'sorry; excuse me; I apologize' },
  { front: 'không có gì', back: 'you\'re welcome; it\'s nothing; don\'t mention it' },
  { front: 'làm ơn', back: 'please (making a request)' },
  { front: 'hẹn gặp lại', back: 'see you again; until we meet again' },
  { front: 'bạn khỏe không', back: 'how are you?' },
  { front: 'tôi khỏe', back: 'I\'m fine/well' },
  { front: 'chúc mừng', back: 'congratulations' },
  { front: 'chúc mừng sinh nhật', back: 'happy birthday' },
  { front: 'chúc mừng năm mới', back: 'happy new year' },
  { front: 'xin chào buổi sáng', back: 'good morning' },
  { front: 'xin chào buổi tối', back: 'good evening' },
  { front: 'tất nhiên', back: 'of course; certainly; naturally' },

  // Question words
  { front: 'ai', back: 'who' },
  { front: 'gì', back: 'what' },
  { front: 'đâu', back: 'where' },
  { front: 'khi nào', back: 'when' },
  { front: 'tại sao', back: 'why' },
  { front: 'như thế nào', back: 'how; in what way' },
  { front: 'bao nhiêu', back: 'how much; how many' },
  { front: 'nào', back: 'which; what kind' },
  { front: 'mấy', back: 'how many (small number); a few' },
  { front: 'bao lâu', back: 'how long (time)' },
  { front: 'bao giờ', back: 'when (future or past)' },
  { front: 'sao', back: 'why (informal); how; star' },

  // Numbers 0–10
  { front: 'rưỡi', back: 'half; and a half; thirty minutes past' },
  { front: 'một', back: 'one' },
  { front: 'hai', back: 'two' },
  { front: 'ba', back: 'three' },
  { front: 'bốn', back: 'four' },
  { front: 'năm', back: 'five; year' },
  { front: 'sáu', back: 'six' },
  { front: 'bảy', back: 'seven' },
  { front: 'tám', back: 'eight' },
  { front: 'chín', back: 'nine' },
  { front: 'mười', back: 'ten' },

  // Numbers 11+ and counting
  { front: 'mười một', back: 'eleven' },
  { front: 'mười hai', back: 'twelve' },
  { front: 'mười lăm', back: 'fifteen' },
  { front: 'hai mươi', back: 'twenty' },
  { front: 'ba mươi', back: 'thirty' },
  { front: 'một trăm', back: 'one hundred' },
  { front: 'một nghìn', back: 'one thousand' },
  { front: 'một triệu', back: 'one million' },
  { front: 'thứ nhất', back: 'first (ordinal)' },
  { front: 'lần', back: 'time(s); occasion; instance' },
  { front: 'cặp', back: 'pair; couple (objects)' },
  { front: 'đôi', back: 'pair; couple' },
  { front: 'tá', back: 'dozen' },
  { front: 'số', back: 'number; figure; quantity' },

  // Time — periods of day
  { front: 'buổi sáng', back: 'morning' },
  { front: 'buổi trưa', back: 'midday; noon' },
  { front: 'buổi chiều', back: 'afternoon; early evening' },
  { front: 'buổi tối', back: 'evening; nighttime' },
  { front: 'đêm', back: 'night' },
  { front: 'bình minh', back: 'dawn; sunrise' },
  { front: 'hoàng hôn', back: 'dusk; sunset' },
  { front: 'giờ', back: 'hour; o\'clock; time' },
  { front: 'phút', back: 'minute' },
  { front: 'giây', back: 'second (time unit)' },
  { front: 'tuần', back: 'week' },
  { front: 'tháng', back: 'month' },
  { front: 'thế kỷ', back: 'century' },
  { front: 'kỷ nguyên', back: 'era; epoch; age' },
  { front: 'thập kỷ', back: 'decade' },
  { front: 'ngày', back: 'day' },

  // Days of week & seasons
  { front: 'thứ hai', back: 'Monday; second (ordinal)' },
  { front: 'thứ ba', back: 'Tuesday' },
  { front: 'thứ tư', back: 'Wednesday' },
  { front: 'thứ năm', back: 'Thursday' },
  { front: 'thứ sáu', back: 'Friday' },
  { front: 'thứ bảy', back: 'Saturday' },
  { front: 'chủ nhật', back: 'Sunday' },
  { front: 'mùa xuân', back: 'spring (season)' },
  { front: 'mùa hè', back: 'summer' },
  { front: 'mùa thu', back: 'autumn; fall' },
  { front: 'mùa đông', back: 'winter' },

  // Time expressions
  { front: 'hôm nay', back: 'today' },
  { front: 'hôm qua', back: 'yesterday' },
  { front: 'ngày mai', back: 'tomorrow' },
  { front: 'bây giờ', back: 'now; at this moment' },
  { front: 'lúc này', back: 'right now; at this time' },
  { front: 'sau', back: 'after; later; behind' },
  { front: 'trước', back: 'before; in front of; ago' },
  { front: 'sớm', back: 'early; soon' },
  { front: 'muộn', back: 'late' },
  { front: 'cuối cùng', back: 'finally; at last; in the end' },
  { front: 'đột ngột', back: 'suddenly; abruptly' },
  { front: 'thường xuyên', back: 'often; frequently; regularly' },
  { front: 'đôi khi', back: 'sometimes; occasionally' },
  { front: 'hiếm khi', back: 'rarely; seldom' },
  { front: 'luôn luôn', back: 'always; all the time' },
  { front: 'không bao giờ', back: 'never' },
  { front: 'vẫn', back: 'still; yet; nevertheless' },
  { front: 'nhanh chóng', back: 'quickly; promptly; rapidly' },

  // Family
  { front: 'gia đình', back: 'family' },
  { front: 'bố', back: 'father (informal)' },
  { front: 'mẹ', back: 'mother' },
  { front: 'cha', back: 'father (formal)' },
  { front: 'con', back: 'child; son/daughter' },
  { front: 'anh trai', back: 'older brother' },
  { front: 'chị gái', back: 'older sister' },
  { front: 'em trai', back: 'younger brother' },
  { front: 'em gái', back: 'younger sister' },
  { front: 'ông nội', back: 'paternal grandfather' },
  { front: 'bà nội', back: 'paternal grandmother' },
  { front: 'ông ngoại', back: 'maternal grandfather' },
  { front: 'bà ngoại', back: 'maternal grandmother' },
  { front: 'chồng', back: 'husband' },
  { front: 'vợ', back: 'wife' },
  { front: 'con trai', back: 'son; boy' },
  { front: 'con gái', back: 'daughter; girl' },
  { front: 'cháu', back: 'grandchild; niece; nephew' },
  { front: 'họ hàng', back: 'relatives; extended family' },
  { front: 'tổ tiên', back: 'ancestors; forebears' },

  // People & social roles
  { front: 'người', back: 'person; people' },
  { front: 'đàn ông', back: 'man; male' },
  { front: 'phụ nữ', back: 'woman; female' },
  { front: 'trẻ em', back: 'children; child' },
  { front: 'bạn bè', back: 'friends' },
  { front: 'đồng nghiệp', back: 'colleague; coworker' },
  { front: 'hàng xóm', back: 'neighbor' },
  { front: 'khách', back: 'guest; customer; visitor' },
  { front: 'chủ', back: 'owner; host; master' },
  { front: 'bạn trai', back: 'boyfriend' },
  { front: 'bạn gái', back: 'girlfriend' },
  { front: 'vua', back: 'king' },
  { front: 'hoàng hậu', back: 'queen' },
  { front: 'chính phủ', back: 'government' },
  { front: 'công dân', back: 'citizen' },

  // Home spaces
  { front: 'nhà', back: 'house; home' },
  { front: 'phòng', back: 'room' },
  { front: 'bếp', back: 'kitchen' },
  { front: 'phòng ngủ', back: 'bedroom' },
  { front: 'phòng khách', back: 'living room' },
  { front: 'phòng tắm', back: 'bathroom' },
  { front: 'nhà vệ sinh', back: 'toilet; restroom' },
  { front: 'sân', back: 'yard; courtyard' },
  { front: 'ban công', back: 'balcony; terrace' },
  { front: 'cửa', back: 'door; entrance' },
  { front: 'cửa sổ', back: 'window' },
  { front: 'mái nhà', back: 'roof; rooftop' },

  // City & public places
  { front: 'trường học', back: 'school (building/institution)' },
  { front: 'bệnh viện', back: 'hospital' },
  { front: 'chợ', back: 'market' },
  { front: 'siêu thị', back: 'supermarket' },
  { front: 'cửa hàng', back: 'store; shop' },
  { front: 'ngân hàng', back: 'bank' },
  { front: 'bưu điện', back: 'post office' },
  { front: 'khách sạn', back: 'hotel' },
  { front: 'nhà hàng', back: 'restaurant' },
  { front: 'quán cà phê', back: 'coffee shop; café' },
  { front: 'công viên', back: 'park' },
  { front: 'đường', back: 'road; street; way; sugar' },
  { front: 'phố', back: 'street; avenue (urban)' },
  { front: 'thành phố', back: 'city' },
  { front: 'làng', back: 'village' },
  { front: 'tỉnh', back: 'province' },
  { front: 'quốc gia', back: 'country; nation' },
  { front: 'thủ đô', back: 'capital city' },
  { front: 'trung tâm', back: 'center; downtown; central' },
  { front: 'ngoại ô', back: 'suburb; outskirts' },
  { front: 'khu phố', back: 'neighborhood; district' },
  { front: 'quảng trường', back: 'square; plaza' },
  { front: 'sân bay', back: 'airport' },

  // Nature
  { front: 'trời', back: 'sky; weather; heaven' },
  { front: 'mặt trời', back: 'sun' },
  { front: 'mặt trăng', back: 'moon' },
  { front: 'ngôi sao', back: 'star' },
  { front: 'mây', back: 'cloud' },
  { front: 'mưa', back: 'rain' },
  { front: 'gió', back: 'wind' },
  { front: 'bão', back: 'storm; typhoon' },
  { front: 'tuyết', back: 'snow' },
  { front: 'lửa', back: 'fire' },
  { front: 'nước', back: 'water; country; nation' },
  { front: 'đất', back: 'earth; soil; ground' },
  { front: 'núi', back: 'mountain' },
  { front: 'sông', back: 'river' },
  { front: 'biển', back: 'sea; ocean' },
  { front: 'hồ', back: 'lake' },
  { front: 'rừng', back: 'forest; jungle' },
  { front: 'cây', back: 'tree; plant' },
  { front: 'hoa', back: 'flower' },
  { front: 'cỏ', back: 'grass' },
  { front: 'lá', back: 'leaf; leaves' },
  { front: 'rễ', back: 'root (plant)' },
  { front: 'đá', back: 'rock; stone' },
  { front: 'cát', back: 'sand' },
  { front: 'không khí', back: 'air' },
  { front: 'ánh sáng', back: 'light; sunlight' },
  { front: 'bóng tối', back: 'darkness; shadow' },
  { front: 'cầu vồng', back: 'rainbow' },
  { front: 'thác nước', back: 'waterfall' },
  { front: 'sa mạc', back: 'desert' },

  // Grains & staples
  { front: 'thức ăn', back: 'food' },
  { front: 'cơm', back: 'cooked rice; meal' },
  { front: 'bún', back: 'rice vermicelli noodles' },
  { front: 'phở', back: 'pho; Vietnamese rice noodle soup' },
  { front: 'bánh mì', back: 'bread; Vietnamese baguette sandwich' },
  { front: 'bánh', back: 'cake; pastry; cookie; bread' },
  { front: 'mì', back: 'wheat noodles; ramen-style noodles' },
  { front: 'gạo', back: 'raw/uncooked rice' },
  { front: 'bột', back: 'flour; powder' },
  { front: 'đậu', back: 'bean; legume; pea' },
  { front: 'đậu phụ', back: 'tofu; bean curd' },
  { front: 'ngô', back: 'corn; maize' },
  { front: 'khoai tây', back: 'potato' },
  { front: 'khoai lang', back: 'sweet potato' },
  { front: 'sắn', back: 'cassava; manioc' },

  // Meat & seafood
  { front: 'thịt', back: 'meat' },
  { front: 'thịt bò', back: 'beef' },
  { front: 'thịt lợn', back: 'pork' },
  { front: 'thịt gà', back: 'chicken (meat)' },
  { front: 'thịt vịt', back: 'duck meat' },
  { front: 'cá', back: 'fish' },
  { front: 'tôm', back: 'shrimp; prawn' },
  { front: 'cua', back: 'crab' },
  { front: 'mực', back: 'squid; cuttlefish' },
  { front: 'sò', back: 'clam; shellfish' },
  { front: 'trứng', back: 'egg' },
  { front: 'xúc xích', back: 'sausage' },

  // Vegetables & fruit
  { front: 'rau', back: 'vegetables; leafy greens' },
  { front: 'rau cải', back: 'cabbage; leafy greens' },
  { front: 'cà chua', back: 'tomato' },
  { front: 'cà rốt', back: 'carrot' },
  { front: 'hành', back: 'onion; green onion' },
  { front: 'tỏi', back: 'garlic' },
  { front: 'ớt', back: 'chili pepper' },
  { front: 'dưa chuột', back: 'cucumber' },
  { front: 'bí đao', back: 'winter melon; ash gourd' },
  { front: 'hoa quả', back: 'fruit' },
  { front: 'cam', back: 'orange (fruit)' },
  { front: 'chuối', back: 'banana' },
  { front: 'táo', back: 'apple' },
  { front: 'xoài', back: 'mango' },
  { front: 'dứa', back: 'pineapple' },
  { front: 'nho', back: 'grape' },
  { front: 'dâu tây', back: 'strawberry' },
  { front: 'dừa', back: 'coconut' },

  // Condiments & cooking
  { front: 'muối', back: 'salt' },
  { front: 'đường cát', back: 'sugar (granulated)' },
  { front: 'dầu ăn', back: 'cooking oil' },
  { front: 'nước mắm', back: 'fish sauce' },
  { front: 'nước tương', back: 'soy sauce' },
  { front: 'giấm', back: 'vinegar' },
  { front: 'tiêu', back: 'pepper (spice)' },
  { front: 'hạt nêm', back: 'seasoning powder; bouillon' },
  { front: 'bơ', back: 'butter' },
  { front: 'gia vị', back: 'spices; seasoning; condiments' },

  // Drinks
  { front: 'đồ uống', back: 'beverage; drink; something to drink' },
  { front: 'sữa', back: 'milk' },
  { front: 'cà phê', back: 'coffee' },
  { front: 'trà', back: 'tea' },
  { front: 'nước cam', back: 'orange juice' },
  { front: 'nước ngọt', back: 'soft drink; soda' },
  { front: 'bia', back: 'beer' },
  { front: 'rượu', back: 'alcohol; wine; liquor' },
  { front: 'sinh tố', back: 'smoothie; fruit shake' },
  { front: 'nước đá', back: 'ice water; iced drink; ice' },

  // Vietnamese dishes
  { front: 'canh', back: 'Vietnamese-style soup; broth' },
  { front: 'cơm rang', back: 'fried rice' },
  { front: 'bún bò Huế', back: 'spicy beef noodle soup from Hue' },
  { front: 'bánh xèo', back: 'sizzling crepe; Vietnamese savory pancake' },
  { front: 'gỏi cuốn', back: 'fresh spring rolls' },
  { front: 'chả giò', back: 'fried spring rolls' },
  { front: 'bún chả', back: 'grilled pork with rice noodles' },
  { front: 'cơm tấm', back: 'broken rice with grilled pork' },
  { front: 'chè', back: 'sweet dessert soup; sweet beverage' },
  { front: 'bánh cuốn', back: 'steamed rice rolls' },

  // Clothing
  { front: 'quần áo', back: 'clothing; clothes' },
  { front: 'áo', back: 'shirt; top; blouse' },
  { front: 'quần', back: 'pants; trousers' },
  { front: 'váy', back: 'skirt; dress' },
  { front: 'áo khoác', back: 'jacket; coat' },
  { front: 'áo dài', back: 'traditional Vietnamese long dress' },
  { front: 'giày', back: 'shoes' },
  { front: 'dép', back: 'sandals; flip-flops' },
  { front: 'tất', back: 'socks; stockings' },
  { front: 'mũ', back: 'hat; cap' },
  { front: 'túi', back: 'bag; pocket' },
  { front: 'ví', back: 'wallet' },
  { front: 'thắt lưng', back: 'belt' },
  { front: 'găng tay', back: 'gloves' },
  { front: 'khăn', back: 'scarf; towel; cloth' },
  { front: 'kính mắt', back: 'glasses; eyewear' },
  { front: 'đồng hồ', back: 'watch; clock' },
  { front: 'vòng cổ', back: 'necklace' },
  { front: 'nhẫn', back: 'ring (jewelry)' },
  { front: 'khuyên tai', back: 'earring' },

  // Animals
  { front: 'con chó', back: 'dog' },
  { front: 'con mèo', back: 'cat' },
  { front: 'con chim', back: 'bird' },
  { front: 'con bò', back: 'cow; cattle' },
  { front: 'con lợn', back: 'pig' },
  { front: 'con gà', back: 'chicken' },
  { front: 'con vịt', back: 'duck' },
  { front: 'con ngựa', back: 'horse' },
  { front: 'con hổ', back: 'tiger' },
  { front: 'con sư tử', back: 'lion' },
  { front: 'con voi', back: 'elephant' },
  { front: 'con khỉ', back: 'monkey' },
  { front: 'con rắn', back: 'snake' },
  { front: 'con thỏ', back: 'rabbit' },
  { front: 'con chuột', back: 'mouse; rat' },
  { front: 'con ếch', back: 'frog' },
  { front: 'bướm', back: 'butterfly' },
  { front: 'con kiến', back: 'ant' },
  { front: 'con ong', back: 'bee' },
  { front: 'con muỗi', back: 'mosquito' },
  { front: 'con gấu', back: 'bear' },
  { front: 'hươu', back: 'deer' },
  { front: 'con sóc', back: 'squirrel' },
  { front: 'con rùa', back: 'turtle; tortoise' },
  { front: 'con cá vàng', back: 'goldfish' },

  // Body parts
  { front: 'đầu', back: 'head' },
  { front: 'mặt', back: 'face; side; aspect' },
  { front: 'mắt', back: 'eye(s)' },
  { front: 'tai', back: 'ear(s)' },
  { front: 'mũi', back: 'nose' },
  { front: 'miệng', back: 'mouth' },
  { front: 'răng', back: 'tooth; teeth' },
  { front: 'lưỡi', back: 'tongue' },
  { front: 'tóc', back: 'hair (on head)' },
  { front: 'cổ', back: 'neck; throat' },
  { front: 'vai', back: 'shoulder' },
  { front: 'tay', back: 'arm; hand' },
  { front: 'ngón tay', back: 'finger' },
  { front: 'ngực', back: 'chest; breast' },
  { front: 'bụng', back: 'stomach; belly; abdomen' },
  { front: 'lưng', back: 'back (body)' },
  { front: 'hông', back: 'hip; waist' },
  { front: 'chân', back: 'leg; foot' },
  { front: 'đầu gối', back: 'knee' },
  { front: 'bàn chân', back: 'foot (the body part)' },
  { front: 'ngón chân', back: 'toe' },
  { front: 'tim', back: 'heart' },
  { front: 'não', back: 'brain' },
  { front: 'xương', back: 'bone' },
  { front: 'da', back: 'skin' },

  // Health & medicine
  { front: 'sức khỏe', back: 'health' },
  { front: 'bệnh', back: 'illness; disease; sick' },
  { front: 'thuốc', back: 'medicine; drug; medication' },
  { front: 'bác sĩ', back: 'doctor; physician' },
  { front: 'y tá', back: 'nurse' },
  { front: 'đau', back: 'pain; hurt; ache; painful' },
  { front: 'sốt', back: 'fever' },
  { front: 'ho', back: 'cough; to cough' },
  { front: 'cảm lạnh', back: 'cold (illness)' },
  { front: 'dị ứng', back: 'allergy; allergic reaction' },
  { front: 'phẫu thuật', back: 'surgery; operation' },
  { front: 'tiêm', back: 'injection; shot; to inject' },
  { front: 'băng bó', back: 'bandage; dressing; to bandage' },
  { front: 'khỏe mạnh', back: 'healthy; fit; in good health' },
  { front: 'yếu', back: 'weak; feeble; frail' },
  { front: 'mệt mỏi', back: 'tired; exhausted; fatigued' },
  { front: 'nghỉ ngơi', back: 'to rest; rest; relaxation' },
  { front: 'tập thể dục', back: 'exercise; to exercise; work out' },
  { front: 'dinh dưỡng', back: 'nutrition; nourishment' },
  { front: 'bảo hiểm y tế', back: 'health insurance' },

  // Education
  { front: 'trường', back: 'school; educational institution' },
  { front: 'lớp học', back: 'classroom; class' },
  { front: 'bài học', back: 'lesson' },
  { front: 'bài tập', back: 'homework; exercise; assignment' },
  { front: 'kiểm tra', back: 'test; exam; to check; to inspect' },
  { front: 'thi', back: 'exam; to take an exam' },
  { front: 'điểm', back: 'score; point; grade; dot' },
  { front: 'học sinh', back: 'pupil; school student' },
  { front: 'sinh viên', back: 'university/college student' },
  { front: 'giáo viên', back: 'teacher' },
  { front: 'thầy giáo', back: 'male teacher' },
  { front: 'cô giáo', back: 'female teacher' },
  { front: 'hiệu trưởng', back: 'principal; headmaster' },
  { front: 'thư viện', back: 'library' },
  { front: 'sách giáo khoa', back: 'textbook' },
  { front: 'bảng', back: 'board; blackboard; table; chart' },
  { front: 'bút', back: 'pen; pencil' },
  { front: 'vở', back: 'notebook; exercise book' },
  { front: 'học bổng', back: 'scholarship' },
  { front: 'tốt nghiệp', back: 'to graduate; graduation' },

  // Work & business
  { front: 'công việc', back: 'work; job; task' },
  { front: 'làm việc', back: 'to work' },
  { front: 'nhân viên', back: 'employee; staff member' },
  { front: 'giám đốc', back: 'director; manager; CEO' },
  { front: 'sếp', back: 'boss (informal)' },
  { front: 'lương', back: 'salary; wages' },
  { front: 'tiền thưởng', back: 'bonus; reward payment' },
  { front: 'hợp đồng', back: 'contract; agreement' },
  { front: 'họp', back: 'meeting; to meet (officially)' },
  { front: 'dự án', back: 'project' },
  { front: 'khách hàng', back: 'customer; client' },
  { front: 'sản phẩm', back: 'product' },
  { front: 'dịch vụ', back: 'service' },
  { front: 'thị trường', back: 'market (commercial)' },
  { front: 'kinh doanh', back: 'business; commerce; trade' },
  { front: 'nghề nghiệp', back: 'occupation; profession; career' },
  { front: 'nghỉ phép', back: 'leave; day off; vacation' },
  { front: 'tuyển dụng', back: 'recruitment; to hire' },
  { front: 'phỏng vấn', back: 'interview; to interview' },
  { front: 'kinh nghiệm', back: 'experience' },
  { front: 'kỹ năng', back: 'skill; ability' },
  { front: 'tăng lương', back: 'raise; salary increase' },
  { front: 'từ chức', back: 'to resign; resignation' },
  { front: 'nghỉ hưu', back: 'to retire; retirement' },
  { front: 'văn phòng', back: 'office' },

  // Transportation
  { front: 'xe', back: 'vehicle (general)' },
  { front: 'xe ô tô', back: 'car; automobile' },
  { front: 'xe máy', back: 'motorbike; scooter' },
  { front: 'xe đạp', back: 'bicycle' },
  { front: 'xe buýt', back: 'bus' },
  { front: 'xe tải', back: 'truck' },
  { front: 'tàu hỏa', back: 'train' },
  { front: 'tàu thuyền', back: 'boat; ship' },
  { front: 'máy bay', back: 'airplane' },
  { front: 'taxi', back: 'taxi; cab' },
  { front: 'trạm', back: 'station; stop; base' },
  { front: 'bến xe', back: 'bus station; bus terminal' },
  { front: 'nhà ga', back: 'train station' },
  { front: 'bến tàu', back: 'port; harbor; dock' },
  { front: 'đường cao tốc', back: 'highway; expressway' },
  { front: 'cầu', back: 'bridge' },
  { front: 'hầm', back: 'tunnel' },
  { front: 'xăng', back: 'gasoline; petrol' },
  { front: 'đỗ xe', back: 'to park (a vehicle)' },
  { front: 'lái xe', back: 'to drive; driver' },

  // Technology
  { front: 'điện thoại', back: 'phone; telephone' },
  { front: 'máy tính', back: 'computer' },
  { front: 'internet', back: 'internet' },
  { front: 'mạng', back: 'network; web; internet' },
  { front: 'email', back: 'email' },
  { front: 'tin nhắn', back: 'message; text message' },
  { front: 'trang web', back: 'website' },
  { front: 'ứng dụng', back: 'application; app' },
  { front: 'phần mềm', back: 'software' },
  { front: 'máy ảnh', back: 'camera' },
  { front: 'tivi', back: 'television; TV' },
  { front: 'đài phát thanh', back: 'radio; radio station' },
  { front: 'pin', back: 'battery' },
  { front: 'sạc', back: 'charger; to charge (battery)' },
  { front: 'wifi', back: 'wifi; wireless internet' },
  { front: 'mật khẩu', back: 'password' },
  { front: 'tài khoản', back: 'account (online/bank)' },
  { front: 'mạng xã hội', back: 'social media; social network' },
  { front: 'tải xuống', back: 'to download' },
  { front: 'tải lên', back: 'to upload' },

  // House & furniture
  { front: 'bàn', back: 'table; desk' },
  { front: 'ghế', back: 'chair; seat' },
  { front: 'giường', back: 'bed' },
  { front: 'tủ', back: 'wardrobe; cabinet; closet' },
  { front: 'kệ', back: 'shelf; rack' },
  { front: 'gương', back: 'mirror' },
  { front: 'thảm', back: 'carpet; rug' },
  { front: 'rèm', back: 'curtain; drape' },
  { front: 'đèn', back: 'lamp; light; lantern' },
  { front: 'quạt', back: 'fan; electric fan' },
  { front: 'điều hòa', back: 'air conditioner' },
  { front: 'tủ lạnh', back: 'refrigerator; fridge' },
  { front: 'lò vi sóng', back: 'microwave oven' },
  { front: 'máy giặt', back: 'washing machine' },
  { front: 'bồn tắm', back: 'bathtub' },
  { front: 'bồn rửa', back: 'sink; basin' },
  { front: 'lò', back: 'stove; furnace; oven; kiln' },
  { front: 'chảo', back: 'frying pan; wok' },
  { front: 'nồi', back: 'pot; saucepan' },
  { front: 'bát', back: 'bowl' },

  // Emotions & feelings
  { front: 'hạnh phúc', back: 'happiness; happy' },
  { front: 'tình yêu', back: 'love (romantic)' },
  { front: 'hy vọng', back: 'hope; to hope' },
  { front: 'ước mơ', back: 'dream; wish; aspiration' },
  { front: 'lo lắng', back: 'worry; anxiety; to worry' },
  { front: 'căng thẳng', back: 'stress; tense; nervous' },
  { front: 'bình tĩnh', back: 'calm; composure; to calm down' },
  { front: 'tự tin', back: 'confidence; confident; self-assured' },
  { front: 'xấu hổ', back: 'shame; embarrassed; ashamed' },
  { front: 'tự hào', back: 'pride; proud' },
  { front: 'ghen tị', back: 'jealousy; envy; jealous' },
  { front: 'thất vọng', back: 'disappointment; disappointed' },
  { front: 'ngạc nhiên', back: 'surprise; surprised; astonished' },
  { front: 'vui mừng', back: 'joy; delighted; elated' },
  { front: 'hài lòng', back: 'satisfaction; satisfied; content' },
  { front: 'bất mãn', back: 'dissatisfaction; discontented' },
  { front: 'chán nản', back: 'boredom; discouraged; fed up' },
  { front: 'cô đơn', back: 'loneliness; lonely' },
  { front: 'hồi hộp', back: 'nervousness; anxious anticipation; excited/nervous' },
  { front: 'thoải mái', back: 'comfort; comfortable; relaxed' },
  { front: 'khó chịu', back: 'discomfort; uncomfortable; annoyed' },
  { front: 'tức giận', back: 'anger; angry; furious' },
  { front: 'yêu thích', back: 'to like; favorite; fondness' },
  { front: 'đam mê', back: 'passion; passionate about' },
  { front: 'kiên nhẫn', back: 'patience; patient' },

  // Colors
  { front: 'đỏ', back: 'red' },
  { front: 'xanh lá', back: 'green (leaf green)' },
  { front: 'xanh dương', back: 'blue (ocean/dark blue)' },
  { front: 'vàng', back: 'yellow; gold (color)' },
  { front: 'màu cam', back: 'orange (color)' },
  { front: 'tím', back: 'purple; violet' },
  { front: 'hồng', back: 'pink' },
  { front: 'nâu', back: 'brown' },
  { front: 'đen', back: 'black' },
  { front: 'trắng', back: 'white' },
  { front: 'xám', back: 'gray; grey' },
  { front: 'be', back: 'beige; cream' },
  { front: 'bạc', back: 'silver (color); silver (metal)' },
  { front: 'xanh lơ', back: 'light blue; sky blue' },
  { front: 'xanh lá cây', back: 'green (plant/nature green)' },

  // Core verbs
  { front: 'là', back: 'to be; is/am/are' },
  { front: 'tồn tại', back: 'to exist; existence; to be present' },
  { front: 'đi', back: 'to go' },
  { front: 'đến', back: 'to come; to arrive; to reach' },
  { front: 'về', back: 'to return; to go home; about; regarding' },
  { front: 'ăn', back: 'to eat' },
  { front: 'uống', back: 'to drink' },
  { front: 'nói', back: 'to say; to speak; to tell' },
  { front: 'nghe', back: 'to listen; to hear' },
  { front: 'nhìn', back: 'to look; to see; to observe' },
  { front: 'xem', back: 'to watch; to see; to view' },
  { front: 'làm', back: 'to do; to make; to work' },
  { front: 'biết', back: 'to know (a fact)' },
  { front: 'hiểu', back: 'to understand' },
  { front: 'muốn', back: 'to want' },
  { front: 'cần', back: 'to need' },
  { front: 'thích', back: 'to like; to enjoy' },
  { front: 'yêu', back: 'to love' },
  { front: 'ghét', back: 'to hate; to dislike strongly' },
  { front: 'sợ', back: 'to be afraid; to fear; afraid' },
  { front: 'nghĩ', back: 'to think' },
  { front: 'nhớ', back: 'to remember; to miss (someone)' },
  { front: 'quên', back: 'to forget' },
  { front: 'học', back: 'to study; to learn' },
  { front: 'dạy', back: 'to teach' },
  { front: 'đọc', back: 'to read' },
  { front: 'viết', back: 'to write' },
  { front: 'mua', back: 'to buy; to purchase' },
  { front: 'bán', back: 'to sell' },
  { front: 'cho', back: 'to give; for' },
  { front: 'lấy', back: 'to take; to get' },
  { front: 'mang', back: 'to carry; to bring; to wear' },
  { front: 'gặp', back: 'to meet' },
  { front: 'hỏi', back: 'to ask' },
  { front: 'trả lời', back: 'to answer; to reply' },
  { front: 'giúp', back: 'to help' },
  { front: 'mở', back: 'to open' },
  { front: 'đóng', back: 'to close; to shut' },
  { front: 'bắt đầu', back: 'to begin; to start' },
  { front: 'kết thúc', back: 'to finish; to end' },
  { front: 'chờ', back: 'to wait' },
  { front: 'gọi', back: 'to call; to name; to order (food)' },
  { front: 'nấu', back: 'to cook' },
  { front: 'sửa', back: 'to fix; to repair; to correct' },
  { front: 'chạy', back: 'to run' },
  { front: 'đứng', back: 'to stand' },
  { front: 'ngồi', back: 'to sit' },
  { front: 'nằm', back: 'to lie down' },
  { front: 'ngủ', back: 'to sleep' },
  { front: 'thức dậy', back: 'to wake up' },
  { front: 'đi bộ', back: 'to walk (on foot)' },
  { front: 'bay', back: 'to fly' },
  { front: 'bơi', back: 'to swim' },
  { front: 'nhảy', back: 'to jump; to dance' },
  { front: 'hát', back: 'to sing' },
  { front: 'chơi', back: 'to play' },
  { front: 'nghỉ', back: 'to rest; to take a break; to be off work' },
  { front: 'tìm', back: 'to find; to look for; to search' },
  { front: 'mất', back: 'to lose; to be lost; to spend (time)' },
  { front: 'thấy', back: 'to see; to find; to feel' },
  { front: 'nói chuyện', back: 'to talk; to chat; to converse' },
  { front: 'gửi', back: 'to send' },
  { front: 'nhận', back: 'to receive; to accept' },
  { front: 'đặt', back: 'to place; to put; to book/reserve' },
  { front: 'trả', back: 'to return; to pay back; to pay' },
  { front: 'vay', back: 'to borrow (money)' },
  { front: 'mượn', back: 'to borrow (objects/things)' },
  { front: 'tặng', back: 'to give as a gift; to donate' },
  { front: 'chia sẻ', back: 'to share' },
  { front: 'tham gia', back: 'to participate; to join' },
  { front: 'rời đi', back: 'to leave; to depart' },
  { front: 'trở lại', back: 'to come back; to return' },
  { front: 'tiếp tục', back: 'to continue' },
  { front: 'dừng lại', back: 'to stop' },
  { front: 'tăng', back: 'to increase; to rise; to raise' },
  { front: 'giảm', back: 'to decrease; to reduce; to lower' },
  { front: 'quyết định', back: 'to decide; decision' },
  { front: 'lựa chọn', back: 'to choose; choice; option' },
  { front: 'giải quyết', back: 'to solve; to resolve; to handle' },
  { front: 'thay đổi', back: 'to change; change; alteration' },

  // More verbs
  { front: 'nhận ra', back: 'to recognize; to realize; to identify' },
  { front: 'phát hiện', back: 'to discover; to detect' },
  { front: 'khám phá', back: 'to explore; to discover' },
  { front: 'tạo ra', back: 'to create; to produce; to generate' },
  { front: 'xây dựng', back: 'to build; to construct; to develop' },
  { front: 'phá hủy', back: 'to destroy; to demolish' },
  { front: 'sửa chữa', back: 'to repair; to fix; to correct' },
  { front: 'cải thiện', back: 'to improve; to better' },
  { front: 'kiểm soát', back: 'to control; to manage; to regulate' },
  { front: 'quản lý', back: 'to manage; to administer; management' },
  { front: 'tổ chức', back: 'to organize; to arrange; organization' },
  { front: 'so sánh', back: 'to compare' },
  { front: 'đánh giá', back: 'to evaluate; to assess; to judge' },
  { front: 'khen ngợi', back: 'to praise; to compliment' },
  { front: 'khuyến khích', back: 'to encourage; to motivate' },
  { front: 'hỗ trợ', back: 'to support; to assist; to back up' },
  { front: 'bảo vệ', back: 'to protect; to defend' },
  { front: 'đồng ý', back: 'to agree; to consent' },
  { front: 'từ chối', back: 'to refuse; to decline; to reject' },
  { front: 'đề xuất', back: 'to propose; to suggest; proposal' },
  { front: 'thảo luận', back: 'to discuss; discussion' },
  { front: 'thuyết phục', back: 'to persuade; to convince' },
  { front: 'giải thích', back: 'to explain; explanation' },
  { front: 'mô tả', back: 'to describe; description' },
  { front: 'kể chuyện', back: 'to tell a story; to narrate' },
  { front: 'báo cáo', back: 'to report; report' },
  { front: 'thông báo', back: 'to announce; announcement; notice' },
  { front: 'cảnh báo', back: 'to warn; warning' },
  { front: 'hứa hẹn', back: 'to promise; promise' },
  { front: 'cam kết', back: 'to commit; commitment' },
  { front: 'thực hiện', back: 'to carry out; to implement; to perform' },
  { front: 'hoàn thành', back: 'to complete; to finish; to accomplish' },
  { front: 'tiến hành', back: 'to proceed; to conduct; to carry out' },
  { front: 'nghiên cứu', back: 'to research; research; to study' },
  { front: 'phân tích', back: 'to analyze; analysis' },
  { front: 'tổng hợp', back: 'to synthesize; to summarize; synthesis' },
  { front: 'liên lạc', back: 'to contact; to keep in touch' },
  { front: 'hẹn gặp', back: 'to make an appointment; appointment; date' },
  { front: 'bật', back: 'to turn on; to activate; to switch on' },
  { front: 'tắt', back: 'to turn off; to switch off; to extinguish' },

  // Adjectives
  { front: 'tốt', back: 'good; well; fine' },
  { front: 'xấu', back: 'bad; ugly; poor quality' },
  { front: 'đẹp', back: 'beautiful; pretty; nice-looking' },
  { front: 'to', back: 'big; large; loud (sound)' },
  { front: 'nhỏ', back: 'small; little; minor' },
  { front: 'cao', back: 'tall; high; loud (volume)' },
  { front: 'thấp', back: 'short (height); low' },
  { front: 'dài', back: 'long' },
  { front: 'ngắn', back: 'short (length)' },
  { front: 'nhanh', back: 'fast; quick; rapid' },
  { front: 'chậm', back: 'slow' },
  { front: 'mới', back: 'new; fresh; recent' },
  { front: 'cũ', back: 'old (things); used; former' },
  { front: 'trẻ', back: 'young' },
  { front: 'già', back: 'old (person or animal)' },
  { front: 'vui', back: 'happy; joyful; fun' },
  { front: 'buồn', back: 'sad; unhappy; sorrowful' },
  { front: 'tức', back: 'angry; irritated; annoyed' },
  { front: 'mệt', back: 'tired; weary' },
  { front: 'đói', back: 'hungry' },
  { front: 'khát', back: 'thirsty' },
  { front: 'nóng', back: 'hot' },
  { front: 'lạnh', back: 'cold' },
  { front: 'ấm', back: 'warm' },
  { front: 'mát', back: 'cool; refreshing' },
  { front: 'khó', back: 'difficult; hard' },
  { front: 'dễ', back: 'easy; simple' },
  { front: 'đúng', back: 'correct; right; true' },
  { front: 'sai', back: 'wrong; incorrect; false' },
  { front: 'nhiều', back: 'many; much; a lot' },
  { front: 'ít', back: 'few; little; not much' },
  { front: 'đủ', back: 'enough; sufficient' },
  { front: 'quan trọng', back: 'important; significant' },
  { front: 'thú vị', back: 'interesting; exciting; fun' },
  { front: 'nguy hiểm', back: 'dangerous; hazardous' },
  { front: 'an toàn', back: 'safe; secure' },
  { front: 'miễn phí', back: 'free (of charge); no cost' },
  { front: 'đắt', back: 'expensive; costly' },
  { front: 'rẻ', back: 'cheap; inexpensive' },
  { front: 'nặng', back: 'heavy; severe (figurative)' },
  { front: 'nhẹ', back: 'light (not heavy); gentle; minor' },
  { front: 'sạch', back: 'clean' },
  { front: 'bẩn', back: 'dirty' },
  { front: 'rộng', back: 'wide; spacious; broad' },
  { front: 'hẹp', back: 'narrow' },
  { front: 'gần', back: 'near; close; nearby' },
  { front: 'xa', back: 'far; distant' },
  { front: 'thật', back: 'real; genuine; truly' },
  { front: 'giả', back: 'fake; false; artificial' },
  { front: 'đơn giản', back: 'simple; plain; straightforward' },
  { front: 'phức tạp', back: 'complex; complicated' },
  { front: 'ngọt', back: 'sweet' },
  { front: 'cay', back: 'spicy; hot (taste)' },
  { front: 'đắng', back: 'bitter' },
  { front: 'chua', back: 'sour; acidic' },
  { front: 'mặn', back: 'salty' },
  { front: 'thơm', back: 'fragrant; aromatic' },
  { front: 'sáng', back: 'bright; light (brightness); morning' },
  { front: 'tối', back: 'dark; dim; evening' },
  { front: 'trung bình', back: 'average; medium; moderate' },

  // Prepositions, conjunctions, particles
  { front: 'và', back: 'and' },
  { front: 'hoặc', back: 'or' },
  { front: 'nhưng', back: 'but; however' },
  { front: 'vì', back: 'because; for (reason)' },
  { front: 'nên', back: 'so; therefore; should' },
  { front: 'nếu', back: 'if; in case' },
  { front: 'khi', back: 'when; while; as' },
  { front: 'ở', back: 'at; in; to live (at a place)' },
  { front: 'trong', back: 'in; inside; within' },
  { front: 'ngoài', back: 'outside; besides; in addition to' },
  { front: 'trên', back: 'on; above; upper' },
  { front: 'dưới', back: 'under; below; lower' },
  { front: 'giữa', back: 'between; among; in the middle of' },
  { front: 'bên cạnh', back: 'next to; beside; alongside' },
  { front: 'với', back: 'with; together with' },
  { front: 'từ', back: 'from; since; word' },
  { front: 'cho đến', back: 'until; up to; as far as' },
  { front: 'qua', back: 'through; past; across; via' },
  { front: 'theo', back: 'according to; following; along with' },
  { front: 'cùng', back: 'together; with; also; as well' },
  { front: 'để', back: 'to (purpose); in order to; to put/place' },
  { front: 'mà', back: 'but; yet; which/that (relative clause)' },
  { front: 'hay', back: 'or; interesting; good (informal)' },
  { front: 'dù', back: 'even though; despite; although' },
  { front: 'mặc dù', back: 'although; even though; despite' },
  { front: 'bởi vì', back: 'because; due to; owing to' },
  { front: 'do đó', back: 'therefore; for that reason; thus' },
  { front: 'vì vậy', back: 'so; therefore; thus' },
  { front: 'của', back: 'of; belonging to; \'s (possessive marker)' },
  { front: 'liên quan đến', back: 'regarding; concerning; related to; about' },

  // Sports & recreation
  { front: 'thể thao', back: 'sports; athletics' },
  { front: 'bóng đá', back: 'soccer; football' },
  { front: 'bóng rổ', back: 'basketball' },
  { front: 'bóng chuyền', back: 'volleyball' },
  { front: 'cầu lông', back: 'badminton' },
  { front: 'bơi lội', back: 'swimming (sport)' },
  { front: 'chạy bộ', back: 'jogging; running (exercise)' },
  { front: 'leo núi', back: 'mountain climbing; hiking' },
  { front: 'du lịch', back: 'travel; tourism; to travel' },
  { front: 'kỳ nghỉ', back: 'vacation; holiday; break' },
  { front: 'trò chơi', back: 'game' },
  { front: 'cờ vua', back: 'chess' },
  { front: 'câu cá', back: 'fishing; to fish' },
  { front: 'nhảy múa', back: 'dancing; to dance' },
  { front: 'vẽ tranh', back: 'painting; drawing; to paint' },
  { front: 'làm vườn', back: 'gardening; to garden' },
  { front: 'yoga', back: 'yoga' },
  { front: 'tập gym', back: 'gym workout; weight training' },
  { front: 'đội', back: 'team; group' },
  { front: 'giải đấu', back: 'tournament; competition; league' },

  // Society & culture
  { front: 'văn hóa', back: 'culture' },
  { front: 'truyền thống', back: 'tradition; traditional' },
  { front: 'phong tục', back: 'custom; tradition; social practice' },
  { front: 'lễ hội', back: 'festival; celebration; ceremony' },
  { front: 'tôn giáo', back: 'religion' },
  { front: 'chính trị', back: 'politics; political' },
  { front: 'luật pháp', back: 'law; legal system' },
  { front: 'quyền lợi', back: 'rights; benefits; interests' },
  { front: 'nghĩa vụ', back: 'duty; obligation' },
  { front: 'xã hội', back: 'society; social' },
  { front: 'cộng đồng', back: 'community' },
  { front: 'dân tộc', back: 'ethnic group; nation; people' },
  { front: 'ngôn ngữ', back: 'language' },
  { front: 'lịch sử', back: 'history; historical' },
  { front: 'nghệ thuật', back: 'art; artistic' },
  { front: 'văn học', back: 'literature' },
  { front: 'kiến trúc', back: 'architecture' },
  { front: 'kinh tế', back: 'economy; economics' },
  { front: 'tài chính', back: 'finance; financial' },
  { front: 'thuế', back: 'tax' },

  // Weather & environment
  { front: 'nắng', back: 'sunshine; sunny' },
  { front: 'lũ lụt', back: 'flood; flooding' },
  { front: 'hạn hán', back: 'drought' },
  { front: 'nhiệt độ', back: 'temperature' },
  { front: 'độ ẩm', back: 'humidity' },
  { front: 'áp suất', back: 'pressure; atmospheric pressure' },
  { front: 'dự báo thời tiết', back: 'weather forecast' },
  { front: 'thời tiết', back: 'weather' },
  { front: 'khí hậu', back: 'climate' },
  { front: 'môi trường', back: 'environment' },
  { front: 'ô nhiễm', back: 'pollution; polluted' },
  { front: 'tái chế', back: 'recycling; to recycle' },
  { front: 'năng lượng', back: 'energy; power' },
  { front: 'rác thải', back: 'waste; garbage; trash' },
  { front: 'sinh thái', back: 'ecology; ecosystem' },

  // Shopping & commerce
  { front: 'mua sắm', back: 'shopping; to shop' },
  { front: 'giá cả', back: 'price; prices' },
  { front: 'hóa đơn', back: 'invoice; bill; receipt' },
  { front: 'thẻ tín dụng', back: 'credit card' },
  { front: 'tiền mặt', back: 'cash' },
  { front: 'giảm giá', back: 'discount; sale; to reduce price' },
  { front: 'khuyến mãi', back: 'promotion; special offer' },
  { front: 'trả lại', back: 'to return (merchandise); to give back' },
  { front: 'bảo hành', back: 'warranty; guarantee' },
  { front: 'chất lượng', back: 'quality' },
  { front: 'thương hiệu', back: 'brand; trademark' },
  { front: 'kích cỡ', back: 'size' },
  { front: 'hàng hóa', back: 'goods; merchandise' },
  { front: 'vận chuyển', back: 'shipping; transportation; delivery' },
  { front: 'hải quan', back: 'customs (border control)' },

  // Abstract concepts
  { front: 'thời gian', back: 'time; period' },
  { front: 'không gian', back: 'space; area; place' },
  { front: 'ý tưởng', back: 'idea; concept' },
  { front: 'vấn đề', back: 'problem; issue; question' },
  { front: 'giải pháp', back: 'solution' },
  { front: 'kết quả', back: 'result; outcome' },
  { front: 'nguyên nhân', back: 'cause; reason' },
  { front: 'phương pháp', back: 'method; approach' },
  { front: 'mục tiêu', back: 'goal; objective; target' },
  { front: 'kế hoạch', back: 'plan; schedule' },
  { front: 'chiến lược', back: 'strategy; strategic' },
  { front: 'cơ hội', back: 'opportunity; chance' },
  { front: 'thách thức', back: 'challenge' },
  { front: 'rủi ro', back: 'risk' },
  { front: 'lợi ích', back: 'benefit; advantage; profit' },
  { front: 'sự thật', back: 'truth; fact; reality' },
  { front: 'thông tin', back: 'information; data' },
  { front: 'kiến thức', back: 'knowledge' },
  { front: 'sáng tạo', back: 'creativity; creative; to create' },
  { front: 'đổi mới', back: 'innovation; to innovate; reform' },
  { front: 'phát triển', back: 'development; to develop; growth' },
  { front: 'tiến bộ', back: 'progress; to progress; advancement' },
  { front: 'thành công', back: 'success; successful' },
  { front: 'thất bại', back: 'failure; to fail; defeat' },
  { front: 'tự do', back: 'freedom; liberty; free' },
  { front: 'bình đẳng', back: 'equality; equal' },
  { front: 'công bằng', back: 'fairness; just; fair' },
  { front: 'hòa bình', back: 'peace' },
  { front: 'hợp tác', back: 'cooperation; to cooperate' },
  { front: 'cạnh tranh', back: 'competition; to compete' },

  // Communication
  { front: 'cuộc trò chuyện', back: 'conversation; chat' },
  { front: 'thư', back: 'letter; mail' },
  { front: 'cuộc gọi', back: 'phone call; call' },
  { front: 'tin tức', back: 'news' },
  { front: 'quảng cáo', back: 'advertisement; advertising' },
  { front: 'bài phát biểu', back: 'speech; address' },
  { front: 'thuyết trình', back: 'presentation; to present' },
  { front: 'hội nghị', back: 'conference' },
  { front: 'hội thảo', back: 'seminar; workshop' },
  { front: 'diễn đàn', back: 'forum' },
  { front: 'phương tiện truyền thông', back: 'media; means of communication' },
  { front: 'kênh', back: 'channel' },
  { front: 'bình luận', back: 'comment; commentary; to comment' },
  { front: 'phản hồi', back: 'feedback; response; to respond' },
  { front: 'lời khuyên', back: 'advice; counsel; recommendation' },

  // Common grammatical/misc words
  { front: 'cách', back: 'way; method; distance; manner' },
  { front: 'loại', back: 'type; kind; category; to remove' },
  { front: 'kiểu', back: 'style; type; manner; design' },
  { front: 'phần', back: 'part; portion; section' },
  { front: 'điều', back: 'thing; matter (abstract); point' },
  { front: 'việc', back: 'thing; matter; task; job; affair' },
  { front: 'chỗ', back: 'place; spot; seat; space' },
  { front: 'nơi', back: 'place; location' },
  { front: 'đợt', back: 'batch; round; wave; period' },
  { front: 'hồi', back: 'time; period; episode; act (in a play)' },
  { front: 'trong khi', back: 'while; meanwhile; during' },
  { front: 'mặt khác', back: 'on the other hand' },
  { front: 'ngoài ra', back: 'besides; furthermore; in addition' },
  { front: 'hơn nữa', back: 'moreover; furthermore; additionally' },
  { front: 'ví dụ', back: 'example; for example' },
  { front: 'chẳng hạn', back: 'for instance; such as; for example' },
  { front: 'nói chung', back: 'in general; generally speaking' },
  { front: 'thực ra', back: 'actually; in fact; in reality' },
  { front: 'thực tế', back: 'reality; in practice; practical; actual' },
  { front: 'tóm lại', back: 'in summary; in conclusion; to sum up' },
  { front: 'bất kỳ', back: 'any; whichever; whatever' },
  { front: 'mỗi', back: 'each; every' },
  { front: 'từng', back: 'each; individual; used to; once' },
  { front: 'các', back: 'the (plural marker); various' },
  { front: 'cũng', back: 'also; too; as well; either' },
  { front: 'đã', back: 'already; past tense marker' },
  { front: 'sẽ', back: 'will; future tense marker; shall' },
  { front: 'đang', back: 'currently; present progressive marker' },
  { front: 'chưa', back: 'not yet; have not; yet' },
  { front: 'lại', back: 'again; also; but; to return' },

  // More adjectives
  { front: 'mạnh', back: 'strong; powerful; intense' },
  { front: 'mạnh mẽ', back: 'strong; powerful; vigorous; forceful' },
  { front: 'cứng', back: 'hard; rigid; tough' },
  { front: 'mềm', back: 'soft; tender; flexible' },
  { front: 'trơn', back: 'smooth; slippery' },
  { front: 'nhám', back: 'rough; coarse; abrasive' },
  { front: 'sắc', back: 'sharp; keen; bright (color)' },
  { front: 'cùn', back: 'blunt; dull; not sharp' },
  { front: 'trong suốt', back: 'transparent; clear; crystal-clear' },
  { front: 'đục', back: 'opaque; murky; cloudy' },
  { front: 'trầm trọng', back: 'serious; severe; critical; grave' },
  { front: 'nhẹ nhàng', back: 'gentle; delicate; soft; lightly' },
  { front: 'đầy đủ', back: 'complete; adequate; sufficient; fully' },
  { front: 'thiếu', back: 'lacking; insufficient; to lack' },
  { front: 'đặc biệt', back: 'special; particular; especially' },
  { front: 'bình thường', back: 'normal; ordinary; usual' },
  { front: 'chính xác', back: 'accurate; precise; exact' },
  { front: 'kỹ lưỡng', back: 'thorough; careful; meticulous' },
  { front: 'tỉ mỉ', back: 'detailed; meticulous; painstaking' },
  { front: 'sáng suốt', back: 'wise; clear-headed; discerning' },
  { front: 'thông minh', back: 'intelligent; smart; clever' },
  { front: 'ngốc', back: 'stupid; foolish; dumb' },
  { front: 'khéo léo', back: 'skillful; dexterous; tactful' },
  { front: 'vụng về', back: 'clumsy; awkward; unskilled' },
  { front: 'dũng cảm', back: 'brave; courageous' },
  { front: 'nhút nhát', back: 'timid; shy; cowardly' },
  { front: 'hào phóng', back: 'generous; liberal; lavish' },
  { front: 'ích kỷ', back: 'selfish; self-centered' },
  { front: 'trung thực', back: 'honest; truthful; sincere' },
  { front: 'gian lận', back: 'dishonest; cheating; fraudulent' },
  { front: 'lịch sự', back: 'polite; courteous' },
  { front: 'thô lỗ', back: 'rude; crude; impolite' },
  { front: 'khiêm tốn', back: 'modest; humble' },
  { front: 'kiêu ngạo', back: 'arrogant; haughty' },
  { front: 'thoáng đãng', back: 'airy; open; spacious' },
  { front: 'chật chội', back: 'cramped; crowded; tight' },
  { front: 'tươi', back: 'fresh; bright; cheerful' },
  { front: 'héo', back: 'wilted; withered; faded' },
  { front: 'chín chắn', back: 'mature; thoughtful; well-considered; prudent' },
  { front: 'sống động', back: 'lively; vibrant; vivid; animated' },

  // More verbs
  { front: 'hưởng', back: 'to enjoy; to benefit from' },
  { front: 'trải nghiệm', back: 'to experience; experience' },
  { front: 'nhận thức', back: 'to perceive; to be aware of; awareness' },
  { front: 'phản ứng', back: 'to react; reaction; response' },
  { front: 'thích nghi', back: 'to adapt; to adjust; to acclimate' },
  { front: 'dự đoán', back: 'to predict; prediction; forecast' },
  { front: 'lên kế hoạch', back: 'to plan; to schedule; planning' },
  { front: 'chuẩn bị', back: 'to prepare; preparation' },
  { front: 'thu thập', back: 'to collect; to gather' },
  { front: 'xử lý', back: 'to process; to handle; to deal with' },
  { front: 'lọc', back: 'to filter; to purify; to strain' },
  { front: 'hiển thị', back: 'to display; to show' },
  { front: 'ẩn', back: 'to hide; hidden; concealed' },
  { front: 'kết nối', back: 'to connect; connection' },
  { front: 'ngắt kết nối', back: 'to disconnect' },
  { front: 'cài đặt', back: 'to install; to set up; settings' },
  { front: 'xóa', back: 'to delete; to erase; to remove' },
  { front: 'phục hồi', back: 'to recover; to restore; recovery' },
  { front: 'sao lưu', back: 'to back up; backup' },
  { front: 'cập nhật', back: 'to update; update' },
  { front: 'nâng cấp', back: 'to upgrade' },
  { front: 'định dạng', back: 'to format; format' },
  { front: 'in', back: 'to print; to stamp' },
  { front: 'sao chép', back: 'to copy; to duplicate' },
  { front: 'dán', back: 'to paste; to stick; to glue' },
  { front: 'cắt', back: 'to cut; to trim; to slice' },
  { front: 'chuyển', back: 'to transfer; to move; to shift' },
  { front: 'chuyển đổi', back: 'to convert; to switch; to transform' },
  { front: 'mở rộng', back: 'to expand; to extend; to enlarge' },
  { front: 'thu nhỏ', back: 'to shrink; to reduce; to minimize' },
  { front: 'hợp nhất', back: 'to merge; to unify; to combine' },
  { front: 'tách', back: 'to separate; to split; to detach; cup (classifier)' },
  { front: 'liên quan', back: 'to be related to; relevant; concerning' },
  { front: 'phụ thuộc', back: 'to depend on; dependent; reliant' },
  { front: 'ảnh hưởng', back: 'to affect; to influence; effect; influence' },

  // Final misc & grammatical words
  { front: 'bản thân', back: 'oneself; self; personally' },
  { front: 'nhau', back: 'each other; one another; together' },
  { front: 'lẫn nhau', back: 'mutually; each other; one another' },
  { front: 'riêng', back: 'separate; private; individual; own' },
  { front: 'chung', back: 'common; shared; together; public' },
  { front: 'thêm', back: 'more; add; additional; extra' },
  { front: 'bớt', back: 'less; to reduce; to remove; decrease' },
  { front: 'chỉ', back: 'only; just; merely; to point' },
  { front: 'cả', back: 'all; both; even; including' },
  { front: 'ngay', back: 'right away; immediately; even; straight' },
  { front: 'đã từng', back: 'have ever; used to; once' },
  { front: 'vừa mới', back: 'just; just now; have just done' },
  { front: 'như', back: 'like; as; such as' },
  { front: 'giống như', back: 'similar to; like; resembling' },
  { front: 'khác', back: 'different; other; another; else' },
  { front: 'nhất', back: 'most; -est (superlative); number one' },
  { front: 'hơn', back: 'more; -er (comparative); more than' },
  { front: 'kém', back: 'less; worse; inferior; poor at' },
  { front: 'bằng', back: 'equal; flat; by means of' },
  { front: 'dùng', back: 'to use; to employ; to consume' },
  { front: 'sử dụng', back: 'to use; to utilize; to make use of' },
  { front: 'cần thiết', back: 'necessary; essential; needed' },
  { front: 'tùy', back: 'up to; depending on; optional; as one pleases' },
  { front: 'tùy thuộc', back: 'depending on; subject to; contingent on' },
  { front: 'dựa vào', back: 'to rely on; to depend on; based on' },
  { front: 'ngoại trừ', back: 'except; apart from; excluding' },
  { front: 'bao gồm', back: 'to include; including; comprising' },
  { front: 'chủ yếu', back: 'mainly; primarily; major' },
  { front: 'phần lớn', back: 'mostly; largely; for the most part' },
  { front: 'cuối', back: 'end; last; final; tail' },
  { front: 'ban đầu', back: 'at first; initially; at the beginning' },
  { front: 'ở giữa', back: 'in the middle; at the center; between' },
  { front: 'khoảng', back: 'about; approximately; around' },
  { front: 'gần đây', back: 'recently; lately; nearby' },
  { front: 'hầu hết', back: 'most; mostly; almost all' },
  { front: 'thường', back: 'usually; often; common; normal' },
  { front: 'lúc nào cũng', back: 'always; at all times; invariably' },
  { front: 'tiền', back: 'money; currency' },
  { front: 'sách', back: 'book' },
  { front: 'điện', back: 'electricity; electric; power' },
]
