import type { SeedCard } from './seedData'

// Vietnamese yoga vocabulary — phrases an instructor or student might say in class
// Front: Vietnamese, Back: English
export const YOGA_SEED_CARDS: SeedCard[] = [
  // Greetings & class start
  { front: 'Xin chào các bạn', back: 'Hello everyone (class greeting)', explanation: '"Các bạn" means "everyone/you all." This is the standard way a yoga instructor greets the class at the start.' },
  { front: 'Chào mừng đến lớp yoga', back: 'Welcome to yoga class', explanation: '"Chào mừng đến" is the welcoming phrase ("welcome to"). "Lớp" means "class."' },
  { front: 'Chúng ta bắt đầu', back: 'Let\'s begin', explanation: '"Chúng ta" is the inclusive "we." "Bắt đầu" means "to begin/start."' },
  { front: 'Hãy ngồi thoải mái', back: 'Sit comfortably', explanation: '"Hãy" is an imperative marker making a polite command. "Thoải mái" means "comfortable/at ease."' },
  { front: 'Nhắm mắt lại', back: 'Close your eyes', explanation: '"Nhắm" means "to close (eyes)." "Lại" adds the sense of closing/shutting. Used at the start of meditation or relaxation.' },
  { front: 'Mở mắt ra', back: 'Open your eyes', explanation: '"Mở" means "to open." "Ra" adds the outward direction. Used when ending meditation or final rest.' },
  { front: 'Thư giãn', back: 'Relax', explanation: 'A Sino-Vietnamese compound meaning "to relax." One of the most frequently used words in a yoga class.' },
  { front: 'Sẵn sàng chưa?', back: 'Are you ready?', explanation: '"Sẵn sàng" means "ready." "Chưa?" is the question particle meaning "yet?" — literally "ready yet?"' },
  { front: 'Bắt đầu nào', back: 'Let\'s start', explanation: '"Nào" at the end adds an encouraging, let\'s-go tone. More casual than "chúng ta bắt đầu."' },

  // Breathing
  { front: 'Hít vào', back: 'Breathe in; inhale', explanation: '"Hít" means "to inhale/sniff in." "Vào" means "in." The most common inhale cue in yoga.' },
  { front: 'Thở ra', back: 'Breathe out; exhale', explanation: '"Thở" is the general verb for breathing. "Ra" means "out." Always paired with "hít vào."' },
  { front: 'Hít thở sâu', back: 'Take a deep breath', explanation: '"Sâu" means "deep." "Hít thở" combines inhale and breathe into one phrase for general breathing.' },
  { front: 'Thở đều', back: 'Breathe evenly; steady breathing', explanation: '"Đều" means "even/steady/uniform." Used when the instructor wants smooth, rhythmic breathing.' },
  { front: 'Giữ hơi thở', back: 'Hold your breath', explanation: '"Giữ" means "hold/keep." "Hơi thở" is the noun for "breath." Used in breath retention exercises.' },
  { front: 'Thở bằng mũi', back: 'Breathe through your nose', explanation: '"Bằng" means "by/through/using." "Mũi" means "nose." Nasal breathing is standard in yoga practice.' },
  { front: 'Thở bằng miệng', back: 'Breathe through your mouth', explanation: '"Miệng" means "mouth." Mouth breathing is occasionally cued for specific releases like lion\'s breath.' },
  { front: 'Hơi thở', back: 'Breath', explanation: 'The noun form of "breath." "Hơi" alone means "air/vapor" and "thở" is "to breathe."' },
  { front: 'Thở chậm lại', back: 'Slow down your breathing', explanation: '"Chậm" means "slow." "Lại" adds the sense of reducing/coming back. Used to transition into calmer segments.' },
  { front: 'Thở tự nhiên', back: 'Breathe naturally', explanation: '"Tự nhiên" means "natural/naturally." Used when returning from controlled breathing to normal rhythm.' },
  { front: 'Tập trung vào hơi thở', back: 'Focus on your breath', explanation: '"Tập trung" means "to focus/concentrate." "Vào" here means "on/into." A key mindfulness cue.' },
  { front: 'Điều hòa hơi thở', back: 'Regulate your breathing', explanation: '"Điều hòa" means "to regulate/harmonize." A more formal term used for pranayama-style exercises.' },

  // Body parts
  { front: 'Cơ thể', back: 'Body', explanation: 'Sino-Vietnamese compound for "body." Used in general cues like "lắng nghe cơ thể" (listen to your body).' },
  { front: 'Đầu', back: 'Head', explanation: 'Basic body part. Also used in compounds: "đau đầu" (headache), "đầu gối" (knee, literally "head of the knee").' },
  { front: 'Cổ', back: 'Neck', explanation: 'Also means "ancient" in other contexts. In yoga, used in cues like "xoay cổ" (neck rolls).' },
  { front: 'Vai', back: 'Shoulder; shoulders', explanation: 'Vietnamese does not mark plural — "vai" is both "shoulder" and "shoulders." Very common in alignment cues.' },
  { front: 'Lưng', back: 'Back (body part)', explanation: 'Refers to the back of the torso. "Thẳng lưng" (straighten your back) is one of the most frequent yoga cues.' },
  { front: 'Ngực', back: 'Chest', explanation: 'Used in cues like "mở ngực ra" (open your chest). Important in backbends and heart-opening poses.' },
  { front: 'Bụng', back: 'Belly; abdomen', explanation: 'The abdominal area. "Siết cơ bụng" (engage your core) is a key strength cue in yoga.' },
  { front: 'Hông', back: 'Hip; hips', explanation: 'Very frequently referenced in yoga for alignment. "Mở hông" (open the hips) is a common class theme.' },
  { front: 'Đầu gối', back: 'Knee; knees', explanation: 'Literally "head of the knee." Often mentioned in safety cues: "cẩn thận đầu gối" (be careful with your knees).' },
  { front: 'Mắt cá chân', back: 'Ankle; ankles', explanation: 'Literally "fish eye of the foot" — referring to the round ankle bone. Used in warm-up rotation exercises.' },
  { front: 'Bàn chân', back: 'Foot; feet', explanation: '"Bàn" means "flat surface." "Bàn chân" is the flat of the foot. Used in grounding and standing pose cues.' },
  { front: 'Ngón chân', back: 'Toe; toes', explanation: '"Ngón" means "digit/finger." "Ngón chân" specifies toes (literally "digits of the foot").' },
  { front: 'Cánh tay', back: 'Arm; arms', explanation: '"Cánh" means "wing." "Cánh tay" is the full arm. Used in poses like Warrior II where arms extend.' },
  { front: 'Khuỷu tay', back: 'Elbow; elbows', explanation: '"Khuỷu" refers to the bend/joint. Referenced in plank and chaturanga alignment cues.' },
  { front: 'Cổ tay', back: 'Wrist; wrists', explanation: 'Literally "neck of the hand." Wrist health is important in weight-bearing poses like plank and downward dog.' },
  { front: 'Bàn tay', back: 'Hand; hands', explanation: '"Bàn tay" is the flat of the hand. "Đặt bàn tay xuống" (place your hands down) is a common cue.' },
  { front: 'Ngón tay', back: 'Finger; fingers', explanation: '"Ngón tay" — digits of the hand. "Xòe ngón tay ra" (spread your fingers) is used in hand placement cues.' },
  { front: 'Xương sống', back: 'Spine', explanation: '"Xương" means "bone" and "sống" means "living/life." Refers to the spine as a whole structure.' },
  { front: 'Cột sống', back: 'Spinal column; backbone', explanation: '"Cột" means "column/pillar." More anatomical than "xương sống." Used in "kéo dài cột sống" (lengthen your spine).' },
  { front: 'Cơ bắp', back: 'Muscle; muscles', explanation: '"Cơ" is the word for muscle tissue. "Cơ bắp" emphasizes muscular strength. Used in strength-building cues.' },
  { front: 'Khớp', back: 'Joint; joints', explanation: 'Refers to any joint in the body. Joint mobility and protection are important themes in yoga instruction.' },
  { front: 'Đùi', back: 'Thigh; thighs', explanation: 'The upper leg. Frequently engaged in standing poses like Warrior and Chair pose.' },
  { front: 'Bắp chân', back: 'Calf; calves (lower leg)', explanation: '"Bắp" means "the fleshy part." Used in stretching cues for the lower leg, especially in downward dog.' },
  { front: 'Xương chậu', back: 'Pelvis', explanation: '"Chậu" means "basin." The pelvis is key in alignment — tilting it correctly affects the whole spine.' },
  { front: 'Cơ hoành', back: 'Diaphragm', explanation: 'The breathing muscle. Understanding diaphragmatic breathing is essential for yoga pranayama practice.' },
  { front: 'Gân', back: 'Tendon; ligament', explanation: 'Connective tissue. Instructors mention "gân" when cautioning students not to overstretch ligaments.' },
  { front: 'Xương', back: 'Bone', explanation: 'General term for bone. Used in alignment cues and when explaining skeletal structure of poses.' },

  // Directions & positions
  { front: 'Lên', back: 'Up', explanation: 'Directional word used constantly: "nâng lên" (lift up), "nhìn lên" (look up), "đưa tay lên" (raise your hands).' },
  { front: 'Xuống', back: 'Down', explanation: 'Opposite of "lên." "Ngồi xuống" (sit down), "hạ xuống" (lower down). One of the most common direction words.' },
  { front: 'Trái', back: 'Left', explanation: 'Left side. "Bên trái" is "the left side." Used when cueing asymmetric poses: "chân trái" (left leg).' },
  { front: 'Phải', back: 'Right', explanation: 'Right side. Also means "must/have to" in other contexts. "Bên phải" is "the right side."' },
  { front: 'Trước', back: 'Forward; front', explanation: 'Means both "forward" (direction) and "front" (position). "Gập người về phía trước" (fold forward).' },
  { front: 'Sau', back: 'Back; behind', explanation: 'The opposite of "trước." "Phía sau" means "behind." Used in cues like "kéo vai ra sau" (pull shoulders back).' },
  { front: 'Sang bên', back: 'To the side', explanation: '"Sang" means "to cross/move over." "Bên" means "side." Used for lateral movements and side bends.' },
  { front: 'Ngang', back: 'Horizontal; sideways', explanation: 'Indicates a horizontal plane. "Đưa tay ngang" means to extend arms horizontally, as in Warrior II.' },
  { front: 'Dọc', back: 'Vertical; lengthwise', explanation: 'Indicates a vertical or lengthwise direction. Opposite of "ngang." Used for spine alignment cues.' },

  // Basic movements
  { front: 'Đứng lên', back: 'Stand up', explanation: '"Đứng" is "to stand." "Lên" adds the upward motion. Used when transitioning from floor to standing sequences.' },
  { front: 'Ngồi xuống', back: 'Sit down', explanation: '"Ngồi" is "to sit." "Xuống" adds the downward motion. Used when moving to seated poses.' },
  { front: 'Nằm xuống', back: 'Lie down', explanation: '"Nằm" means "to lie." Used when transitioning to supine poses or final relaxation (savasana).' },
  { front: 'Quỳ xuống', back: 'Kneel down', explanation: '"Quỳ" means "to kneel." Used for table-top position, camel pose, and other kneeling poses.' },
  { front: 'Nâng lên', back: 'Lift up; raise', explanation: '"Nâng" means "to lift/raise." Used with body parts: "nâng chân lên" (lift your leg), "nâng tay lên" (raise your arms).' },
  { front: 'Hạ xuống', back: 'Lower down', explanation: '"Hạ" means "to lower." The controlled opposite of "nâng lên." Used for slow, mindful lowering in transitions.' },
  { front: 'Giữ', back: 'Hold; maintain', explanation: 'One of the most important verbs in yoga. "Giữ tư thế" (hold the pose), "giữ hơi thở" (hold your breath).' },
  { front: 'Giữ nguyên', back: 'Hold still; stay in position', explanation: '"Nguyên" means "original/unchanged." "Giữ nguyên" emphasizes staying exactly as you are without moving.' },
  { front: 'Xoay', back: 'Rotate; twist', explanation: 'Used for both joint rotations (warm-ups) and twisting poses. "Xoay người" means "twist your body."' },
  { front: 'Nghiêng', back: 'Tilt; lean', explanation: 'A lateral movement. "Nghiêng sang bên" (tilt to the side). Used in side bends and lateral stretches.' },
  { front: 'Gập', back: 'Fold; bend', explanation: '"Gập người" means "fold the body." Used in forward folds like Uttanasana. Implies a hinge-like motion.' },
  { front: 'Duỗi', back: 'Extend; straighten', explanation: 'The opposite of "gập." "Duỗi chân" (extend your leg), "duỗi tay" (extend your arm).' },
  { front: 'Kéo dài', back: 'Lengthen; elongate', explanation: '"Kéo" means "pull" and "dài" means "long." Together: "to make longer." Key cue for spine lengthening.' },
  { front: 'Mở rộng', back: 'Open wide; expand', explanation: '"Mở" is "open" and "rộng" is "wide." Used for chest openers and hip openers: "mở rộng ngực" (expand the chest).' },
  { front: 'Co lại', back: 'Contract; pull in', explanation: '"Co" means "to contract/shrink." "Lại" adds the inward sense. Used for engaging muscles or tucking in.' },
  { front: 'Đẩy', back: 'Push', explanation: 'Used in active cues: "đẩy gót chân xuống" (push your heels down), "đẩy hông lên" (push your hips up).' },
  { front: 'Kéo', back: 'Pull', explanation: 'The opposite of "đẩy." "Kéo vai ra sau" (pull shoulders back). Common in alignment corrections.' },
  { front: 'Siết chặt', back: 'Tighten; squeeze', explanation: '"Siết" means "to tighten" and "chặt" means "tight." Used for engaging specific muscles like glutes or core.' },
  { front: 'Thả lỏng', back: 'Release; let go', explanation: '"Thả" means "to release/drop" and "lỏng" means "loose." The opposite of "siết chặt." Used to cue relaxation.' },
  { front: 'Rướn người', back: 'Stretch up; reach upward', explanation: '"Rướn" means "to stretch/reach upward." Implies an active reaching through the whole body, as in Mountain pose.' },

  // Yoga poses — standing
  { front: 'Tư thế núi', back: 'Mountain pose (Tāḍāsana)', explanation: '"Núi" means "mountain." The foundational standing pose — feet grounded, body tall like a mountain.' },
  { front: 'Tư thế chiến binh một', back: 'Warrior I pose (Vīrabhadrāsana I)', explanation: '"Chiến binh" means "warrior." "Một" is "one." Front knee bent, arms raised overhead, back foot angled.' },
  { front: 'Tư thế chiến binh hai', back: 'Warrior II pose (Vīrabhadrāsana II)', explanation: '"Hai" is "two." Arms extended horizontally, gaze over the front hand. Builds leg strength and stability.' },
  { front: 'Tư thế chiến binh ba', back: 'Warrior III pose (Vīrabhadrāsana III)', explanation: '"Ba" is "three." A balancing pose — standing on one leg with the body and back leg parallel to the floor.' },
  { front: 'Tư thế tam giác', back: 'Triangle pose (Trikoṇāsana)', explanation: '"Tam giác" means "triangle" (Sino-Vietnamese: tam=three, giác=angle). The body forms a triangle shape in this lateral stretch.' },
  { front: 'Tư thế cái cây', back: 'Tree pose (Vṛkṣāsana)', explanation: '"Cái cây" means "a tree." A standing balance pose with one foot on the inner thigh. "Cái" is a classifier for plants/objects.' },
  { front: 'Tư thế ghế', back: 'Chair pose (Utkaṭāsana)', explanation: '"Ghế" means "chair." The body mimics sitting in an invisible chair — knees bent, arms raised.' },
  { front: 'Tư thế đại bàng', back: 'Eagle pose (Garuḍāsana)', explanation: '"Đại bàng" means "eagle." Arms and legs are wrapped/entwined, requiring balance and flexibility.' },
  { front: 'Tư thế nửa mặt trăng', back: 'Half moon pose (Ardha Chandrāsana)', explanation: '"Nửa" means "half" and "mặt trăng" means "moon." A balancing pose with one hand on the floor and the body open to the side.' },
  { front: 'Tư thế gập người đứng', back: 'Standing forward fold (Uttānāsana)', explanation: '"Gập người" means "fold the body" and "đứng" means "standing." A deep hamstring stretch folding from the hips.' },

  // Yoga poses — seated & floor
  { front: 'Tư thế ngồi xếp bằng', back: 'Easy seated pose (Sukhāsana)', explanation: '"Ngồi xếp bằng" means "sit cross-legged." The default seated position for meditation and breathing exercises.' },
  { front: 'Tư thế hoa sen', back: 'Lotus pose (Padmāsana)', explanation: '"Hoa sen" means "lotus flower." Feet placed on opposite thighs. An advanced seated meditation pose.' },
  { front: 'Tư thế em bé', back: 'Child\'s pose (Bālāsana)', explanation: '"Em bé" means "baby/child." A resting pose with knees wide, torso folded forward. Used as a rest at any time.' },
  { front: 'Tư thế con mèo', back: 'Cat pose (Mārjāryāsana)', explanation: '"Con mèo" means "cat." On all fours, rounding the spine upward like a cat stretching. Paired with cow pose.' },
  { front: 'Tư thế con bò', back: 'Cow pose (Bitilāsana)', explanation: '"Con bò" means "cow." On all fours, dropping the belly and lifting the head. Always paired with cat pose for spinal warm-up.' },
  { front: 'Tư thế chó úp mặt', back: 'Downward-facing dog (Adho Mukha Śvānāsana)', explanation: '"Chó" means "dog," "úp" means "facing down," "mặt" means "face." One of the most iconic yoga poses, forming an inverted V.' },
  { front: 'Tư thế chó ngửa mặt', back: 'Upward-facing dog (Ūrdhva Mukha Śvānāsana)', explanation: '"Ngửa" means "facing up." A backbend with straight arms, chest lifted, thighs off the floor.' },
  { front: 'Tư thế rắn hổ mang', back: 'Cobra pose (Bhujaṅgāsana)', explanation: '"Rắn hổ mang" means "cobra (snake)." A gentle backbend — similar to upward dog but with hips on the floor.' },
  { front: 'Tư thế con châu chấu', back: 'Locust pose (Śalabhāsana)', explanation: '"Con châu chấu" means "locust/grasshopper." Lying face down, lifting chest and legs. Strengthens the back.' },
  { front: 'Tư thế cây cầu', back: 'Bridge pose (Setu Bandhāsana)', explanation: '"Cây cầu" means "bridge." Lying on the back, lifting the hips to form a bridge shape. Opens the chest and strengthens legs.' },
  { front: 'Tư thế tấm ván', back: 'Plank pose (Phalakāsana)', explanation: '"Tấm ván" means "plank/board." The body is held straight like a board. Builds core and arm strength.' },
  { front: 'Tư thế tấm ván nghiêng', back: 'Side plank pose (Vasiṣṭhāsana)', explanation: '"Nghiêng" means "tilted/sideways." Balancing on one hand with the body sideways. An advanced arm balance.' },
  { front: 'Tư thế con bồ câu', back: 'Pigeon pose (Eka Pāda Rājakapotāsana)', explanation: '"Con bồ câu" means "pigeon." A deep hip opener with one leg bent forward and the other extended back.' },
  { front: 'Tư thế con thuyền', back: 'Boat pose (Nāvāsana)', explanation: '"Con thuyền" means "boat." Balancing on the sit bones with legs and torso forming a V-shape. A strong core exercise.' },
  { front: 'Tư thế xác chết', back: 'Corpse pose (Śavāsana) — final resting pose', explanation: '"Xác chết" means "corpse." The final relaxation pose, lying completely still. Despite looking easy, it requires full surrender.' },
  { front: 'Tư thế cây nến', back: 'Shoulderstand (Sarvāṅgāsana)', explanation: '"Cây nến" means "candle." The body is held vertical like a candle, supported by the shoulders. An inversion pose.' },
  { front: 'Tư thế cái cày', back: 'Plow pose (Halāsana)', explanation: '"Cái cày" means "plow." From shoulderstand, the legs come over the head with feet touching the floor behind.' },
  { front: 'Tư thế ngồi gập người', back: 'Seated forward fold (Paścimatānāsana)', explanation: '"Ngồi gập người" means "seated body fold." Sitting with legs extended, folding forward from the hips over the legs.' },
  { front: 'Tư thế xoắn ngồi', back: 'Seated spinal twist (Ardha Matsyendrāsana)', explanation: '"Xoắn" means "twist" and "ngồi" means "seated." A deep spinal rotation done while seated. Aids digestion and spinal mobility.' },
  { front: 'Tư thế con cá', back: 'Fish pose (Matsyāsana)', explanation: '"Con cá" means "fish." A backbend done lying down with the chest lifted and head tilted back. Opens the throat and chest.' },
  { front: 'Tư thế cánh cung', back: 'Bow pose (Dhanurāsana)', explanation: '"Cánh cung" means "bow" (archery). Lying face down, holding the ankles and lifting — the body curves like a bow.' },
  { front: 'Tư thế con lạc đà', back: 'Camel pose (Uṣṭrāsana)', explanation: '"Con lạc đà" means "camel." Kneeling and arching backward to reach the heels. A deep backbend that opens the front body.' },
  { front: 'Tư thế vặn xoắn nằm', back: 'Supine spinal twist (Supta Matsyendrāsana)', explanation: '"Vặn xoắn" means "twist" and "nằm" means "lying down." A gentle twist done on the back, usually near the end of class.' },
  { front: 'Tư thế ôm gối', back: 'Knees-to-chest pose (Apānāsana)', explanation: '"Ôm" means "hug/embrace" and "gối" means "knee." Lying on the back hugging the knees to the chest. Relieves lower back tension.' },
  { front: 'Tư thế nằm mở hông', back: 'Reclined bound angle (Supta Baddha Koṇāsana)', explanation: '"Nằm" means "lying" and "mở hông" means "open hips." Lying down with soles of feet together, knees open. A restorative hip opener.' },
  { front: 'Tư thế chân lên tường', back: 'Legs up the wall (Viparīta Karaṇī)', explanation: '"Chân" means "legs," "lên" means "up," "tường" means "wall." A restorative inversion — simply resting legs against a wall.' },

  // Instructor cues — alignment
  { front: 'Thẳng lưng', back: 'Straighten your back', explanation: '"Thẳng" means "straight." One of the most frequently repeated alignment cues in any yoga class.' },
  { front: 'Kéo dài cột sống', back: 'Lengthen your spine', explanation: '"Kéo dài" means "lengthen" and "cột sống" means "spine." Cues the student to create space between vertebrae.' },
  { front: 'Mở ngực ra', back: 'Open your chest', explanation: '"Mở" means "open" and "ra" adds outward direction. Used in backbends and to correct rounded-shoulder posture.' },
  { front: 'Hạ vai xuống', back: 'Lower your shoulders; drop your shoulders', explanation: 'A common correction — students often tense their shoulders up toward their ears. This cue releases that tension.' },
  { front: 'Kéo vai ra sau', back: 'Pull your shoulders back', explanation: '"Ra sau" means "toward the back." Opens the chest and corrects forward-rounding shoulders.' },
  { front: 'Siết cơ bụng', back: 'Engage your core; tighten your abs', explanation: '"Siết" means "tighten" and "cơ bụng" means "abdominal muscles." Core engagement protects the lower back.' },
  { front: 'Đẩy hông về phía trước', back: 'Push your hips forward', explanation: '"Về phía trước" means "toward the front." Used in lunges and backbends to align the pelvis.' },
  { front: 'Kéo hông về phía sau', back: 'Pull your hips back', explanation: '"Về phía sau" means "toward the back." Used in downward dog and forward folds for proper hip hinge.' },
  { front: 'Giữ đầu gối thẳng hàng', back: 'Keep your knees aligned', explanation: '"Thẳng hàng" means "aligned/in line." Prevents knee injuries by keeping knees tracking over toes.' },
  { front: 'Không khóa đầu gối', back: 'Don\'t lock your knees', explanation: '"Khóa" means "to lock." Locking the knees hyperextends the joint. Keep a micro-bend for safety.' },
  { front: 'Hai chân rộng bằng hông', back: 'Feet hip-width apart', explanation: '"Hai chân" means "two legs/feet," "rộng bằng" means "as wide as." A standard standing alignment cue.' },
  { front: 'Hai chân rộng bằng vai', back: 'Feet shoulder-width apart', explanation: 'Same structure as above but "vai" (shoulders) instead of "hông" (hips). A slightly wider stance.' },
  { front: 'Ép gót chân xuống sàn', back: 'Press your heels into the floor', explanation: '"Ép" means "press" and "gót chân" means "heel." "Sàn" means "floor." Key cue in downward dog.' },
  { front: 'Xòe các ngón chân ra', back: 'Spread your toes', explanation: '"Xòe" means "to spread/fan out." Spreading toes improves balance and ground contact in standing poses.' },
  { front: 'Phân bổ trọng lượng đều', back: 'Distribute your weight evenly', explanation: '"Phân bổ" means "distribute," "trọng lượng" means "weight," "đều" means "evenly." A balance and alignment cue.' },
  { front: 'Nhìn thẳng', back: 'Look straight ahead', explanation: '"Nhìn" means "to look." "Thẳng" means "straight." Sets the drishti (gaze point) for balance and focus.' },
  { front: 'Nhìn lên', back: 'Look up', explanation: 'Used in poses like Warrior I or upward salute where the gaze follows the hands overhead.' },
  { front: 'Nhìn xuống', back: 'Look down', explanation: 'Used in forward folds and downward dog. Helps relax the neck and maintain alignment.' },
  { front: 'Cằm hơi thu vào', back: 'Tuck your chin slightly', explanation: '"Cằm" means "chin," "hơi" means "slightly," "thu vào" means "tuck in." Lengthens the back of the neck.' },
  { front: 'Giữ cân bằng', back: 'Keep your balance', explanation: '"Cân bằng" means "balance." Used in one-legged poses like Tree and Warrior III.' },

  // Instructor cues — transitions
  { front: 'Chuyển sang tư thế tiếp theo', back: 'Move to the next pose', explanation: '"Chuyển sang" means "transition to." "Tiếp theo" means "next." A standard sequencing cue.' },
  { front: 'Giữ tư thế này', back: 'Hold this pose', explanation: '"Này" means "this." The instructor asks students to remain in the current position, usually for several breaths.' },
  { front: 'Từ từ', back: 'Slowly; gently', explanation: 'Reduplication of "từ" intensifies the meaning of slowness. Used constantly to encourage mindful, controlled movement.' },
  { front: 'Quay về tư thế ban đầu', back: 'Return to the starting position', explanation: '"Quay về" means "return to." "Ban đầu" means "original/initial." Used to reset between sequences.' },
  { front: 'Đổi bên', back: 'Switch sides', explanation: '"Đổi" means "change/switch" and "bên" means "side." Used after completing a pose on one side of the body.' },
  { front: 'Lặp lại bên kia', back: 'Repeat on the other side', explanation: '"Lặp lại" means "repeat" and "bên kia" means "the other side." Same concept as "đổi bên" but more explicit.' },
  { front: 'Nghỉ một chút', back: 'Rest for a moment', explanation: '"Nghỉ" means "rest" and "một chút" means "a little bit." Often followed by child\'s pose or a brief pause.' },
  { front: 'Uống nước', back: 'Drink water', explanation: '"Uống" means "to drink" and "nước" means "water." Instructors offer water breaks, especially in heated classes.' },
  { front: 'Chào mặt trời', back: 'Sun salutation (Sūrya Namaskāra)', explanation: '"Chào" means "to greet" and "mặt trời" means "the sun." A fundamental yoga flow sequence used as a warm-up.' },
  { front: 'Tiếp tục', back: 'Continue', explanation: 'Means "to continue." Used to keep the flow going without interruption.' },
  { front: 'Dừng lại', back: 'Stop', explanation: '"Dừng" means "to stop" and "lại" reinforces the stopping. Used when students need to pause or hold.' },

  // Instructor cues — effort & awareness
  { front: 'Cố gắng thêm một chút', back: 'Try a little more', explanation: '"Cố gắng" means "to try/effort" and "thêm một chút" means "a little more." Gentle encouragement to push slightly deeper.' },
  { front: 'Đừng ép quá', back: 'Don\'t push too hard; don\'t force it', explanation: '"Đừng" is the negative imperative (don\'t). "Ép" means "force/press." "Quá" means "too much." A safety reminder.' },
  { front: 'Lắng nghe cơ thể', back: 'Listen to your body', explanation: '"Lắng nghe" means "to listen carefully." A core yoga philosophy — respect your body\'s limits and signals.' },
  { front: 'Cảm nhận sự kéo giãn', back: 'Feel the stretch', explanation: '"Cảm nhận" means "to feel/sense." "Sự kéo giãn" is "the stretch." Brings awareness to the physical sensation.' },
  { front: 'Tìm điểm thoải mái', back: 'Find your comfortable edge', explanation: '"Tìm" means "find" and "điểm thoải mái" means "comfortable point." The sweet spot between effort and ease.' },
  { front: 'Giữ sự tập trung', back: 'Maintain your focus', explanation: '"Sự tập trung" is the noun form of "focus/concentration." Helps students stay mentally present during challenging poses.' },
  { front: 'Buông bỏ căng thẳng', back: 'Let go of tension', explanation: '"Buông bỏ" means "to let go/release" and "căng thẳng" means "tension/stress." A relaxation and mindfulness cue.' },
  { front: 'Chú ý đến cảm giác', back: 'Pay attention to sensations', explanation: '"Chú ý" means "pay attention" and "cảm giác" means "sensations/feelings." Cultivates body awareness.' },
  { front: 'Giữ bình tĩnh', back: 'Stay calm', explanation: '"Bình tĩnh" means "calm/composed." Used during challenging holds or when students show frustration.' },
  { front: 'Tập trung vào hiện tại', back: 'Focus on the present moment', explanation: '"Hiện tại" means "the present." A mindfulness cue encouraging students to let go of distracting thoughts.' },

  // Stretching & flexibility
  { front: 'Kéo giãn', back: 'Stretch', explanation: '"Kéo" means "pull" and "giãn" means "to stretch/extend." The general verb for stretching any body part.' },
  { front: 'Khởi động', back: 'Warm up', explanation: '"Khởi" means "to start" and "động" means "movement." The warm-up phase at the beginning of a yoga class.' },
  { front: 'Giãn cơ', back: 'Stretch your muscles', explanation: '"Giãn" means "stretch" and "cơ" means "muscle." More specific than "kéo giãn" — targets muscular flexibility.' },
  { front: 'Kéo giãn chân', back: 'Stretch your legs', explanation: '"Chân" means "leg/foot." Leg stretches are a major component of yoga — hamstrings, quads, and calves.' },
  { front: 'Kéo giãn tay', back: 'Stretch your arms', explanation: '"Tay" means "arm/hand." Arm stretches open the shoulders and prepare for weight-bearing poses.' },
  { front: 'Xoay cổ', back: 'Roll your neck; neck circles', explanation: '"Xoay" means "rotate" and "cổ" means "neck." A common warm-up exercise to release neck tension.' },
  { front: 'Xoay vai', back: 'Roll your shoulders; shoulder circles', explanation: 'Shoulder rolls release tension from sitting or stress. Done forward and backward in warm-ups.' },
  { front: 'Xoay hông', back: 'Circle your hips', explanation: 'Hip circles mobilize the pelvis and lower back. Done standing with hands on hips during warm-up.' },
  { front: 'Xoay cổ tay', back: 'Rotate your wrists', explanation: 'Wrist rotations prepare for weight-bearing on the hands in plank, downward dog, and arm balances.' },
  { front: 'Xoay mắt cá chân', back: 'Rotate your ankles', explanation: 'Ankle rotations improve mobility and warm up the joint before standing balance poses.' },
  { front: 'Dẻo dai', back: 'Flexible; flexibility', explanation: '"Dẻo" means "supple" and "dai" means "enduring/resilient." Describes overall body flexibility developed through practice.' },
  { front: 'Linh hoạt', back: 'Agile; supple', explanation: 'A Sino-Vietnamese word meaning "flexible/agile." Can describe both physical suppleness and mental adaptability.' },

  // Meditation & mindfulness
  { front: 'Thiền', back: 'Meditation; to meditate', explanation: 'A Sino-Vietnamese word from the Chinese "Chan" (Zen). Used as both noun and verb in Vietnamese yoga contexts.' },
  { front: 'Chánh niệm', back: 'Mindfulness', explanation: 'A Buddhist term meaning "right mindfulness." Increasingly used in modern Vietnamese yoga and wellness contexts.' },
  { front: 'Tĩnh tâm', back: 'Calm the mind; inner stillness', explanation: '"Tĩnh" means "still/calm" and "tâm" means "mind/heart." A meditative goal in yoga practice.' },
  { front: 'Tĩnh lặng', back: 'Silence; stillness', explanation: '"Tĩnh" means "still" and "lặng" means "quiet/silent." Describes the quality of silence during meditation.' },
  { front: 'An yên', back: 'Peaceful; serene', explanation: 'Both "an" and "yên" mean "peaceful." The reduplication creates a deeper sense of peace and tranquility.' },
  { front: 'Ý thức', back: 'Awareness; consciousness', explanation: 'A Sino-Vietnamese compound. "Ý" means "mind/intention" and "thức" means "consciousness." Central to mindful practice.' },
  { front: 'Quan sát', back: 'Observe; watch', explanation: '"Quan sát" means "to observe." In meditation, it refers to watching thoughts and sensations without judgment.' },
  { front: 'Buông xả', back: 'Let go; release (mentally)', explanation: '"Buông" means "to release" and "xả" means "to let go." A deeper, more spiritual version of "thả lỏng."' },
  { front: 'Hòa bình nội tâm', back: 'Inner peace', explanation: '"Hòa bình" means "peace" and "nội tâm" means "inner/internal mind." A goal of yoga and meditation practice.' },
  { front: 'Năng lượng', back: 'Energy', explanation: 'A Sino-Vietnamese word for "energy." Used to describe the flow of life force (prana) in yoga philosophy.' },

  // Student questions & requests
  { front: 'Em không hiểu', back: 'I don\'t understand (student to instructor)', explanation: '"Em" is the pronoun a younger person or student uses with a teacher. "Không hiểu" means "don\'t understand."' },
  { front: 'Làm lại được không?', back: 'Can you show that again?', explanation: '"Làm lại" means "do again." "Được không?" is a polite question tag meaning "is it okay?" or "can you?"' },
  { front: 'Chậm hơn được không?', back: 'Can you go slower?', explanation: '"Chậm hơn" means "slower" (comparative with "hơn"). A polite request for the instructor to slow the pace.' },
  { front: 'Em bị đau', back: 'I\'m in pain; it hurts (student)', explanation: '"Bị" indicates an undesirable condition. "Đau" means "pain/hurt." Important safety phrase to communicate to the instructor.' },
  { front: 'Có biến thể dễ hơn không?', back: 'Is there an easier variation?', explanation: '"Biến thể" means "variation/modification." "Dễ hơn" means "easier." Asking for a pose modification.' },
  { front: 'Em không làm được', back: 'I can\'t do it (student)', explanation: '"Không làm được" means "cannot do." Used when a pose is too challenging. The instructor will offer alternatives.' },
  { front: 'Tư thế này giữ bao lâu?', back: 'How long do we hold this pose?', explanation: '"Bao lâu" means "how long?" A practical question about the duration of a held pose.' },
  { front: 'Cần dụng cụ gì?', back: 'What props do I need?', explanation: '"Cần" means "need" and "dụng cụ" means "equipment/tools." "Gì" means "what." Asked before class starts.' },
  { front: 'Phù hợp cho người mới không?', back: 'Is this suitable for beginners?', explanation: '"Phù hợp" means "suitable" and "người mới" means "new person/beginner." A common question when choosing a class.' },
  { front: 'Em có thai, có tập được không?', back: 'I\'m pregnant — can I practice?', explanation: '"Có thai" means "pregnant." An important health question — prenatal yoga requires specific modifications.' },

  // Props & equipment
  { front: 'Thảm yoga', back: 'Yoga mat', explanation: '"Thảm" means "mat/rug." The most essential piece of yoga equipment, providing cushioning and grip.' },
  { front: 'Gạch yoga', back: 'Yoga block', explanation: '"Gạch" means "brick/block." Yoga blocks help bring the floor closer in poses where flexibility is limited.' },
  { front: 'Dây đai yoga', back: 'Yoga strap', explanation: '"Dây đai" means "strap/belt." Used to extend reach in stretches, especially for hamstrings and shoulders.' },
  { front: 'Gối thiền', back: 'Meditation cushion; bolster', explanation: '"Gối" means "pillow/cushion" and "thiền" means "meditation." Elevates the hips for comfortable seated meditation.' },
  { front: 'Chăn', back: 'Blanket', explanation: 'Used for warmth during savasana, as padding under knees, or folded as a seat for meditation.' },
  { front: 'Khăn', back: 'Towel', explanation: 'Used to wipe sweat, especially in hot yoga, or placed over the mat for extra grip.' },
  { front: 'Chai nước', back: 'Water bottle', explanation: '"Chai" means "bottle" and "nước" means "water." Essential to stay hydrated, especially in vigorous or heated classes.' },

  // Class structure
  { front: 'Phần khởi động', back: 'Warm-up section', explanation: '"Phần" means "section/part." The warm-up prepares joints and muscles for deeper work in the main sequence.' },
  { front: 'Phần chính', back: 'Main section; main sequence', explanation: '"Chính" means "main/primary." The core of the class where the most challenging poses are practiced.' },
  { front: 'Giãn hồi', back: 'Cool down', explanation: '"Giãn" means "stretch" and "hồi" means "recovery." The cool-down phase uses gentle stretches to transition toward rest.' },
  { front: 'Thiền cuối buổi', back: 'Closing meditation', explanation: '"Cuối buổi" means "end of session." A seated or lying meditation that closes the practice.' },
  { front: 'Lớp kéo dài bao lâu?', back: 'How long is the class?', explanation: '"Lớp" means "class" and "kéo dài bao lâu" means "lasts how long." Typical classes run 60 or 90 minutes.' },
  { front: 'Buổi tập hôm nay', back: 'Today\'s practice; today\'s session', explanation: '"Buổi tập" means "practice session" and "hôm nay" means "today." Used when the instructor introduces the day\'s focus.' },
  { front: 'Lớp dành cho người mới', back: 'Beginner class', explanation: '"Dành cho" means "intended for" and "người mới" means "new person/beginner." Describes a foundational-level class.' },
  { front: 'Lớp nâng cao', back: 'Advanced class', explanation: '"Nâng cao" means "elevated/advanced." For experienced practitioners with established poses and more complex sequences.' },

  // Sensations & feelings
  { front: 'Đau', back: 'Pain; hurt', explanation: 'Sharp or acute pain is a signal to stop. Distinguish from "mỏi" (muscle soreness), which is normal.' },
  { front: 'Mỏi', back: 'Sore; fatigued (muscles)', explanation: 'Muscle fatigue from effort. Unlike "đau" (pain), mild "mỏi" during practice is normal and expected.' },
  { front: 'Căng', back: 'Tight; tense', explanation: 'Describes muscle tightness. "Căng thẳng" (tense/stressed) uses this word. Yoga aims to release "căng."' },
  { front: 'Thoải mái', back: 'Comfortable; at ease', explanation: 'The goal state in most yoga poses — finding ease within effort. Used in the cue "hãy ngồi thoải mái."' },
  { front: 'Khó chịu', back: 'Uncomfortable; uneasy', explanation: '"Khó" means "difficult" and "chịu" means "to bear/endure." Communicate this feeling to the instructor for modifications.' },
  { front: 'Nóng', back: 'Hot; warm', explanation: 'Can describe body temperature during practice. In hot yoga, the room is intentionally heated.' },
  { front: 'Lạnh', back: 'Cold', explanation: 'Students may feel cold during savasana as the body cools down. Instructors often offer blankets.' },
  { front: 'Mồ hôi', back: 'Sweat', explanation: '"Mồ hôi" is the noun for sweat. Sweating is normal during vigorous yoga sequences like sun salutations.' },
  { front: 'Mệt', back: 'Tired', explanation: 'Feeling tired is normal after an intense class. Rest in child\'s pose if fatigue hits during practice.' },
  { front: 'Khỏe', back: 'Strong; healthy; feeling well', explanation: 'A versatile word meaning "strong," "healthy," or "well." "Khỏe không?" means "How are you?" (literally "well or not?").' },
  { front: 'Nhẹ nhàng', back: 'Light; gentle', explanation: 'Describes gentle movement or a light sensation. "Nhẹ nhàng thôi" means "gently now" — a common instructor cue.' },
  { front: 'Nặng nề', back: 'Heavy; weighed down', explanation: 'Can describe physical heaviness in tired limbs or the grounding sensation sought in restorative poses.' },
  { front: 'Tê', back: 'Numb; tingling', explanation: 'Numbness or tingling may indicate a pinched nerve or poor circulation. Adjust the pose if you feel "tê."' },
  { front: 'Chóng mặt', back: 'Dizzy', explanation: '"Chóng" means "quickly" and "mặt" means "face/surface." Dizziness can occur from inversions or standing up too fast.' },

  // Encouragement
  { front: 'Giỏi lắm', back: 'Very good; well done', explanation: '"Giỏi" means "skilled/good" and "lắm" is an intensifier. A warm compliment from the instructor.' },
  { front: 'Tốt lắm', back: 'Very good; great job', explanation: '"Tốt" means "good" and "lắm" intensifies it. Slightly more general than "giỏi lắm" — praises the result rather than skill.' },
  { front: 'Cố lên', back: 'Keep going; you can do it', explanation: '"Cố" means "to try/persevere" and "lên" adds an upward/forward energy. An encouraging cheer during challenging holds.' },
  { front: 'Đúng rồi', back: 'That\'s right; correct', explanation: '"Đúng" means "correct" and "rồi" means "already." Confirms the student has achieved the right alignment or form.' },
  { front: 'Hoàn hảo', back: 'Perfect', explanation: 'A Sino-Vietnamese word meaning "perfect/flawless." Strong praise for excellent form or effort.' },
  { front: 'Tiến bộ rồi đấy', back: 'You\'re making progress', explanation: '"Tiến bộ" means "progress" and "rồi đấy" adds "already, you know." Acknowledges improvement over previous sessions.' },

  // End of class
  { front: 'Cảm ơn các bạn', back: 'Thank you everyone', explanation: '"Cảm ơn" means "thank you." The instructor thanks the class for their practice and presence.' },
  { front: 'Hẹn gặp lại', back: 'See you again', explanation: '"Hẹn" means "to make an appointment/promise." "Gặp lại" means "meet again." A warm goodbye.' },
  { front: 'Buổi tập kết thúc', back: 'Class is over; session ends', explanation: '"Kết thúc" means "to end/conclude." Formally signals that the practice session has finished.' },
  { front: 'Namaste', back: 'Namaste (greeting/farewell — "the light in me honors the light in you")', explanation: 'A Sanskrit greeting used universally in yoga. In Vietnam, it is borrowed directly and understood in yoga contexts.' },
  { front: 'Chắp tay trước ngực', back: 'Bring hands together at your chest (prayer position)', explanation: '"Chắp tay" means "join/press hands together." "Trước ngực" means "in front of the chest." The Anjali mudra gesture.' },
  { front: 'Cúi chào', back: 'Bow', explanation: '"Cúi" means "to bow/bend forward" and "chào" means "to greet." A respectful bow often accompanying Namaste.' },

  // Counting & timing
  { front: 'Đếm', back: 'Count', explanation: 'The verb "to count." Instructors count breath cycles or seconds to time pose holds.' },
  { front: 'Một', back: 'One', explanation: 'The number one. Vietnamese numbers are straightforward — used for counting reps, breaths, or timing.' },
  { front: 'Hai', back: 'Two', explanation: 'The number two. "Hai" also appears in "hai chân" (two legs/feet) for alignment cues.' },
  { front: 'Ba', back: 'Three', explanation: 'The number three. "Một, hai, ba" is the standard counting sequence used in class.' },
  { front: 'Bốn', back: 'Four', explanation: 'The number four. Used when counting breaths or movements in a sequence.' },
  { front: 'Năm', back: 'Five', explanation: 'The number five. Also means "year." Context makes the meaning clear — in class it is always the number.' },
  { front: 'Mười', back: 'Ten', explanation: 'The number ten. "Giữ mười giây" means "hold for ten seconds."' },
  { front: 'Giây', back: 'Second (time)', explanation: 'A unit of time. Instructors may count holds in seconds: "năm giây nữa" (five more seconds).' },
  { front: 'Phút', back: 'Minute', explanation: 'A unit of time. "Thiền năm phút" means "five minutes of meditation."' },
  { front: 'Năm hơi thở', back: 'Five breaths', explanation: 'Pose holds are often measured in breath cycles. Five breaths is a standard hold duration in vinyasa yoga.' },
  { front: 'Mười hơi thở', back: 'Ten breaths', explanation: 'A longer hold. "Giữ tư thế này mười hơi thở" means "hold this pose for ten breaths."' },

  // Yoga concepts
  { front: 'Yoga', back: 'Yoga — union of body and mind', explanation: 'Borrowed directly from Sanskrit. In Vietnamese, it is pronounced similarly and universally understood.' },
  { front: 'Tư thế', back: 'Pose; posture (asana)', explanation: '"Tư thế" is the Vietnamese translation of "asana." Every pose name begins with "tư thế" + a descriptor.' },
  { front: 'Luồng khí', back: 'Flow of energy; prana', explanation: '"Luồng" means "flow/stream" and "khí" means "air/energy." The Vietnamese equivalent of the Sanskrit "prana."' },
  { front: 'Luân xa', back: 'Chakra — energy center', explanation: 'A Sino-Vietnamese transliteration of "chakra." "Luân" means "wheel" and "xa" means "vehicle." The seven energy centers of the body.' },
  { front: 'Hài hòa', back: 'Harmony; balance', explanation: 'Both syllables mean "harmonious." Describes the balance between body, mind, and spirit that yoga cultivates.' },
  { front: 'Sức mạnh nội tâm', back: 'Inner strength', explanation: '"Sức mạnh" means "strength/power" and "nội tâm" means "inner mind." The mental resilience built through practice.' },
  { front: 'Sự kết nối', back: 'Connection (body-mind)', explanation: '"Sự kết nối" means "the connection." Yoga philosophy emphasizes connecting body, breath, and mind.' },
  { front: 'Cân bằng cơ thể và tâm trí', back: 'Balance of body and mind', explanation: '"Cân bằng" means "balance," "cơ thể" means "body," "và" means "and," "tâm trí" means "mind." The essence of yoga.' },
  { front: 'Biến thể', back: 'Variation; modification (of a pose)', explanation: '"Biến" means "change" and "thể" means "form." Instructors offer variations to make poses accessible to all levels.' },
  { front: 'Nâng cao', back: 'Advanced; to advance', explanation: '"Nâng" means "to raise" and "cao" means "high." Describes advanced variations or higher-level practice.' },

  // Common corrections
  { front: 'Đừng nín thở', back: 'Don\'t hold your breath', explanation: '"Đừng" is "don\'t" and "nín thở" means "hold breath" (suppress breathing). Students often hold their breath in difficult poses.' },
  { front: 'Thả vai xuống', back: 'Relax your shoulders down', explanation: '"Thả" means "release/drop." One of the most common corrections — shoulders creep up during effort.' },
  { front: 'Không gồng cổ', back: 'Don\'t tense your neck', explanation: '"Gồng" means "to tense/strain." Neck tension is common when students try too hard. Keep the neck soft.' },
  { front: 'Giữ hông vuông góc', back: 'Keep your hips square', explanation: '"Vuông góc" means "square/right-angled." Keeping hips square means both hip bones face the same direction.' },
  { front: 'Kéo rốn vào trong', back: 'Draw your navel in', explanation: '"Rốn" means "navel/belly button." Drawing the navel inward engages the deep core muscles (transverse abdominis).' },
  { front: 'Đặt bàn chân phẳng trên sàn', back: 'Place your foot flat on the floor', explanation: '"Đặt" means "place," "phẳng" means "flat," "trên sàn" means "on the floor." Ensures proper grounding.' },
  { front: 'Cẩn thận đầu gối', back: 'Be careful with your knees', explanation: '"Cẩn thận" means "be careful." Knee safety is critical — never push past pain in the knee joint.' },
  { front: 'Đừng so sánh với người khác', back: 'Don\'t compare yourself to others', explanation: '"So sánh" means "compare" and "người khác" means "other people." A key yoga philosophy — practice is personal.' },
]
