import type { SeedCard } from './seedData'

// Vietnamese yoga vocabulary — phrases an instructor or student might say in class
// Front: Vietnamese, Back: English
export const YOGA_SEED_CARDS: SeedCard[] = [
  // Greetings & class start
  { front: 'Xin chào các bạn', back: 'Hello everyone (class greeting)' },
  { front: 'Chào mừng đến lớp yoga', back: 'Welcome to yoga class' },
  { front: 'Chúng ta bắt đầu', back: 'Let\'s begin' },
  { front: 'Hãy ngồi thoải mái', back: 'Sit comfortably' },
  { front: 'Nhắm mắt lại', back: 'Close your eyes' },
  { front: 'Mở mắt ra', back: 'Open your eyes' },
  { front: 'Thư giãn', back: 'Relax' },
  { front: 'Sẵn sàng chưa?', back: 'Are you ready?' },
  { front: 'Bắt đầu nào', back: 'Let\'s start' },

  // Breathing
  { front: 'Hít vào', back: 'Breathe in; inhale' },
  { front: 'Thở ra', back: 'Breathe out; exhale' },
  { front: 'Hít thở sâu', back: 'Take a deep breath' },
  { front: 'Thở đều', back: 'Breathe evenly; steady breathing' },
  { front: 'Giữ hơi thở', back: 'Hold your breath' },
  { front: 'Thở bằng mũi', back: 'Breathe through your nose' },
  { front: 'Thở bằng miệng', back: 'Breathe through your mouth' },
  { front: 'Hơi thở', back: 'Breath' },
  { front: 'Thở chậm lại', back: 'Slow down your breathing' },
  { front: 'Thở tự nhiên', back: 'Breathe naturally' },
  { front: 'Tập trung vào hơi thở', back: 'Focus on your breath' },
  { front: 'Điều hòa hơi thở', back: 'Regulate your breathing' },

  // Body parts
  { front: 'Cơ thể', back: 'Body' },
  { front: 'Đầu', back: 'Head' },
  { front: 'Cổ', back: 'Neck' },
  { front: 'Vai', back: 'Shoulder; shoulders' },
  { front: 'Lưng', back: 'Back (body part)' },
  { front: 'Ngực', back: 'Chest' },
  { front: 'Bụng', back: 'Belly; abdomen' },
  { front: 'Hông', back: 'Hip; hips' },
  { front: 'Đầu gối', back: 'Knee; knees' },
  { front: 'Mắt cá chân', back: 'Ankle; ankles' },
  { front: 'Bàn chân', back: 'Foot; feet' },
  { front: 'Ngón chân', back: 'Toe; toes' },
  { front: 'Cánh tay', back: 'Arm; arms' },
  { front: 'Khuỷu tay', back: 'Elbow; elbows' },
  { front: 'Cổ tay', back: 'Wrist; wrists' },
  { front: 'Bàn tay', back: 'Hand; hands' },
  { front: 'Ngón tay', back: 'Finger; fingers' },
  { front: 'Xương sống', back: 'Spine' },
  { front: 'Cột sống', back: 'Spinal column; backbone' },
  { front: 'Cơ bắp', back: 'Muscle; muscles' },
  { front: 'Khớp', back: 'Joint; joints' },
  { front: 'Đùi', back: 'Thigh; thighs' },
  { front: 'Bắp chân', back: 'Calf; calves (lower leg)' },
  { front: 'Xương chậu', back: 'Pelvis' },
  { front: 'Cơ hoành', back: 'Diaphragm' },
  { front: 'Gân', back: 'Tendon; ligament' },
  { front: 'Xương', back: 'Bone' },

  // Directions & positions
  { front: 'Lên', back: 'Up' },
  { front: 'Xuống', back: 'Down' },
  { front: 'Trái', back: 'Left' },
  { front: 'Phải', back: 'Right' },
  { front: 'Trước', back: 'Forward; front' },
  { front: 'Sau', back: 'Back; behind' },
  { front: 'Sang bên', back: 'To the side' },
  { front: 'Ngang', back: 'Horizontal; sideways' },
  { front: 'Dọc', back: 'Vertical; lengthwise' },

  // Basic movements
  { front: 'Đứng lên', back: 'Stand up' },
  { front: 'Ngồi xuống', back: 'Sit down' },
  { front: 'Nằm xuống', back: 'Lie down' },
  { front: 'Quỳ xuống', back: 'Kneel down' },
  { front: 'Nâng lên', back: 'Lift up; raise' },
  { front: 'Hạ xuống', back: 'Lower down' },
  { front: 'Giữ', back: 'Hold; maintain' },
  { front: 'Giữ nguyên', back: 'Hold still; stay in position' },
  { front: 'Xoay', back: 'Rotate; twist' },
  { front: 'Nghiêng', back: 'Tilt; lean' },
  { front: 'Gập', back: 'Fold; bend' },
  { front: 'Duỗi', back: 'Extend; straighten' },
  { front: 'Kéo dài', back: 'Lengthen; elongate' },
  { front: 'Mở rộng', back: 'Open wide; expand' },
  { front: 'Co lại', back: 'Contract; pull in' },
  { front: 'Đẩy', back: 'Push' },
  { front: 'Kéo', back: 'Pull' },
  { front: 'Siết chặt', back: 'Tighten; squeeze' },
  { front: 'Thả lỏng', back: 'Release; let go' },
  { front: 'Rướn người', back: 'Stretch up; reach upward' },

  // Yoga poses — standing
  { front: 'Tư thế núi', back: 'Mountain pose (Tāḍāsana)' },
  { front: 'Tư thế chiến binh một', back: 'Warrior I pose (Vīrabhadrāsana I)' },
  { front: 'Tư thế chiến binh hai', back: 'Warrior II pose (Vīrabhadrāsana II)' },
  { front: 'Tư thế chiến binh ba', back: 'Warrior III pose (Vīrabhadrāsana III)' },
  { front: 'Tư thế tam giác', back: 'Triangle pose (Trikoṇāsana)' },
  { front: 'Tư thế cái cây', back: 'Tree pose (Vṛkṣāsana)' },
  { front: 'Tư thế ghế', back: 'Chair pose (Utkaṭāsana)' },
  { front: 'Tư thế đại bàng', back: 'Eagle pose (Garuḍāsana)' },
  { front: 'Tư thế nửa mặt trăng', back: 'Half moon pose (Ardha Chandrāsana)' },
  { front: 'Tư thế gập người đứng', back: 'Standing forward fold (Uttānāsana)' },

  // Yoga poses — seated & floor
  { front: 'Tư thế ngồi xếp bằng', back: 'Easy seated pose (Sukhāsana)' },
  { front: 'Tư thế hoa sen', back: 'Lotus pose (Padmāsana)' },
  { front: 'Tư thế em bé', back: 'Child\'s pose (Bālāsana)' },
  { front: 'Tư thế con mèo', back: 'Cat pose (Mārjāryāsana)' },
  { front: 'Tư thế con bò', back: 'Cow pose (Bitilāsana)' },
  { front: 'Tư thế chó úp mặt', back: 'Downward-facing dog (Adho Mukha Śvānāsana)' },
  { front: 'Tư thế chó ngửa mặt', back: 'Upward-facing dog (Ūrdhva Mukha Śvānāsana)' },
  { front: 'Tư thế rắn hổ mang', back: 'Cobra pose (Bhujaṅgāsana)' },
  { front: 'Tư thế con châu chấu', back: 'Locust pose (Śalabhāsana)' },
  { front: 'Tư thế cây cầu', back: 'Bridge pose (Setu Bandhāsana)' },
  { front: 'Tư thế tấm ván', back: 'Plank pose (Phalakāsana)' },
  { front: 'Tư thế tấm ván nghiêng', back: 'Side plank pose (Vasiṣṭhāsana)' },
  { front: 'Tư thế con bồ câu', back: 'Pigeon pose (Eka Pāda Rājakapotāsana)' },
  { front: 'Tư thế con thuyền', back: 'Boat pose (Nāvāsana)' },
  { front: 'Tư thế xác chết', back: 'Corpse pose (Śavāsana) — final resting pose' },
  { front: 'Tư thế cây nến', back: 'Shoulderstand (Sarvāṅgāsana)' },
  { front: 'Tư thế cái cày', back: 'Plow pose (Halāsana)' },
  { front: 'Tư thế ngồi gập người', back: 'Seated forward fold (Paścimatānāsana)' },
  { front: 'Tư thế xoắn ngồi', back: 'Seated spinal twist (Ardha Matsyendrāsana)' },
  { front: 'Tư thế con cá', back: 'Fish pose (Matsyāsana)' },
  { front: 'Tư thế cánh cung', back: 'Bow pose (Dhanurāsana)' },
  { front: 'Tư thế con lạc đà', back: 'Camel pose (Uṣṭrāsana)' },
  { front: 'Tư thế vặn xoắn nằm', back: 'Supine spinal twist (Supta Matsyendrāsana)' },
  { front: 'Tư thế ôm gối', back: 'Knees-to-chest pose (Apānāsana)' },
  { front: 'Tư thế nằm mở hông', back: 'Reclined bound angle (Supta Baddha Koṇāsana)' },
  { front: 'Tư thế chân lên tường', back: 'Legs up the wall (Viparīta Karaṇī)' },

  // Instructor cues — alignment
  { front: 'Thẳng lưng', back: 'Straighten your back' },
  { front: 'Kéo dài cột sống', back: 'Lengthen your spine' },
  { front: 'Mở ngực ra', back: 'Open your chest' },
  { front: 'Hạ vai xuống', back: 'Lower your shoulders; drop your shoulders' },
  { front: 'Kéo vai ra sau', back: 'Pull your shoulders back' },
  { front: 'Siết cơ bụng', back: 'Engage your core; tighten your abs' },
  { front: 'Đẩy hông về phía trước', back: 'Push your hips forward' },
  { front: 'Kéo hông về phía sau', back: 'Pull your hips back' },
  { front: 'Giữ đầu gối thẳng hàng', back: 'Keep your knees aligned' },
  { front: 'Không khóa đầu gối', back: 'Don\'t lock your knees' },
  { front: 'Hai chân rộng bằng hông', back: 'Feet hip-width apart' },
  { front: 'Hai chân rộng bằng vai', back: 'Feet shoulder-width apart' },
  { front: 'Ép gót chân xuống sàn', back: 'Press your heels into the floor' },
  { front: 'Xòe các ngón chân ra', back: 'Spread your toes' },
  { front: 'Phân bổ trọng lượng đều', back: 'Distribute your weight evenly' },
  { front: 'Nhìn thẳng', back: 'Look straight ahead' },
  { front: 'Nhìn lên', back: 'Look up' },
  { front: 'Nhìn xuống', back: 'Look down' },
  { front: 'Cằm hơi thu vào', back: 'Tuck your chin slightly' },
  { front: 'Giữ cân bằng', back: 'Keep your balance' },

  // Instructor cues — transitions
  { front: 'Chuyển sang tư thế tiếp theo', back: 'Move to the next pose' },
  { front: 'Giữ tư thế này', back: 'Hold this pose' },
  { front: 'Từ từ', back: 'Slowly; gently' },
  { front: 'Quay về tư thế ban đầu', back: 'Return to the starting position' },
  { front: 'Đổi bên', back: 'Switch sides' },
  { front: 'Lặp lại bên kia', back: 'Repeat on the other side' },
  { front: 'Nghỉ một chút', back: 'Rest for a moment' },
  { front: 'Uống nước', back: 'Drink water' },
  { front: 'Chào mặt trời', back: 'Sun salutation (Sūrya Namaskāra)' },
  { front: 'Tiếp tục', back: 'Continue' },
  { front: 'Dừng lại', back: 'Stop' },

  // Instructor cues — effort & awareness
  { front: 'Cố gắng thêm một chút', back: 'Try a little more' },
  { front: 'Đừng ép quá', back: 'Don\'t push too hard; don\'t force it' },
  { front: 'Lắng nghe cơ thể', back: 'Listen to your body' },
  { front: 'Cảm nhận sự kéo giãn', back: 'Feel the stretch' },
  { front: 'Tìm điểm thoải mái', back: 'Find your comfortable edge' },
  { front: 'Giữ sự tập trung', back: 'Maintain your focus' },
  { front: 'Buông bỏ căng thẳng', back: 'Let go of tension' },
  { front: 'Chú ý đến cảm giác', back: 'Pay attention to sensations' },
  { front: 'Giữ bình tĩnh', back: 'Stay calm' },
  { front: 'Tập trung vào hiện tại', back: 'Focus on the present moment' },

  // Stretching & flexibility
  { front: 'Kéo giãn', back: 'Stretch' },
  { front: 'Khởi động', back: 'Warm up' },
  { front: 'Giãn cơ', back: 'Stretch your muscles' },
  { front: 'Kéo giãn chân', back: 'Stretch your legs' },
  { front: 'Kéo giãn tay', back: 'Stretch your arms' },
  { front: 'Xoay cổ', back: 'Roll your neck; neck circles' },
  { front: 'Xoay vai', back: 'Roll your shoulders; shoulder circles' },
  { front: 'Xoay hông', back: 'Circle your hips' },
  { front: 'Xoay cổ tay', back: 'Rotate your wrists' },
  { front: 'Xoay mắt cá chân', back: 'Rotate your ankles' },
  { front: 'Dẻo dai', back: 'Flexible; flexibility' },
  { front: 'Linh hoạt', back: 'Agile; supple' },

  // Meditation & mindfulness
  { front: 'Thiền', back: 'Meditation; to meditate' },
  { front: 'Chánh niệm', back: 'Mindfulness' },
  { front: 'Tĩnh tâm', back: 'Calm the mind; inner stillness' },
  { front: 'Tĩnh lặng', back: 'Silence; stillness' },
  { front: 'An yên', back: 'Peaceful; serene' },
  { front: 'Ý thức', back: 'Awareness; consciousness' },
  { front: 'Quan sát', back: 'Observe; watch' },
  { front: 'Buông xả', back: 'Let go; release (mentally)' },
  { front: 'Hòa bình nội tâm', back: 'Inner peace' },
  { front: 'Năng lượng', back: 'Energy' },

  // Student questions & requests
  { front: 'Em không hiểu', back: 'I don\'t understand (student to instructor)' },
  { front: 'Làm lại được không?', back: 'Can you show that again?' },
  { front: 'Chậm hơn được không?', back: 'Can you go slower?' },
  { front: 'Em bị đau', back: 'I\'m in pain; it hurts (student)' },
  { front: 'Có biến thể dễ hơn không?', back: 'Is there an easier variation?' },
  { front: 'Em không làm được', back: 'I can\'t do it (student)' },
  { front: 'Tư thế này giữ bao lâu?', back: 'How long do we hold this pose?' },
  { front: 'Cần dụng cụ gì?', back: 'What props do I need?' },
  { front: 'Phù hợp cho người mới không?', back: 'Is this suitable for beginners?' },
  { front: 'Em có thai, có tập được không?', back: 'I\'m pregnant — can I practice?' },

  // Props & equipment
  { front: 'Thảm yoga', back: 'Yoga mat' },
  { front: 'Gạch yoga', back: 'Yoga block' },
  { front: 'Dây đai yoga', back: 'Yoga strap' },
  { front: 'Gối thiền', back: 'Meditation cushion; bolster' },
  { front: 'Chăn', back: 'Blanket' },
  { front: 'Khăn', back: 'Towel' },
  { front: 'Chai nước', back: 'Water bottle' },

  // Class structure
  { front: 'Phần khởi động', back: 'Warm-up section' },
  { front: 'Phần chính', back: 'Main section; main sequence' },
  { front: 'Giãn hồi', back: 'Cool down' },
  { front: 'Thiền cuối buổi', back: 'Closing meditation' },
  { front: 'Lớp kéo dài bao lâu?', back: 'How long is the class?' },
  { front: 'Buổi tập hôm nay', back: 'Today\'s practice; today\'s session' },
  { front: 'Lớp dành cho người mới', back: 'Beginner class' },
  { front: 'Lớp nâng cao', back: 'Advanced class' },

  // Sensations & feelings
  { front: 'Đau', back: 'Pain; hurt' },
  { front: 'Mỏi', back: 'Sore; fatigued (muscles)' },
  { front: 'Căng', back: 'Tight; tense' },
  { front: 'Thoải mái', back: 'Comfortable; at ease' },
  { front: 'Khó chịu', back: 'Uncomfortable; uneasy' },
  { front: 'Nóng', back: 'Hot; warm' },
  { front: 'Lạnh', back: 'Cold' },
  { front: 'Mồ hôi', back: 'Sweat' },
  { front: 'Mệt', back: 'Tired' },
  { front: 'Khỏe', back: 'Strong; healthy; feeling well' },
  { front: 'Nhẹ nhàng', back: 'Light; gentle' },
  { front: 'Nặng nề', back: 'Heavy; weighed down' },
  { front: 'Tê', back: 'Numb; tingling' },
  { front: 'Chóng mặt', back: 'Dizzy' },

  // Encouragement
  { front: 'Giỏi lắm', back: 'Very good; well done' },
  { front: 'Tốt lắm', back: 'Very good; great job' },
  { front: 'Cố lên', back: 'Keep going; you can do it' },
  { front: 'Đúng rồi', back: 'That\'s right; correct' },
  { front: 'Hoàn hảo', back: 'Perfect' },
  { front: 'Tiến bộ rồi đấy', back: 'You\'re making progress' },

  // End of class
  { front: 'Cảm ơn các bạn', back: 'Thank you everyone' },
  { front: 'Hẹn gặp lại', back: 'See you again' },
  { front: 'Buổi tập kết thúc', back: 'Class is over; session ends' },
  { front: 'Namaste', back: 'Namaste (greeting/farewell — "the light in me honors the light in you")' },
  { front: 'Chắp tay trước ngực', back: 'Bring hands together at your chest (prayer position)' },
  { front: 'Cúi chào', back: 'Bow' },

  // Counting & timing
  { front: 'Đếm', back: 'Count' },
  { front: 'Một', back: 'One' },
  { front: 'Hai', back: 'Two' },
  { front: 'Ba', back: 'Three' },
  { front: 'Bốn', back: 'Four' },
  { front: 'Năm', back: 'Five' },
  { front: 'Mười', back: 'Ten' },
  { front: 'Giây', back: 'Second (time)' },
  { front: 'Phút', back: 'Minute' },
  { front: 'Năm hơi thở', back: 'Five breaths' },
  { front: 'Mười hơi thở', back: 'Ten breaths' },

  // Yoga concepts
  { front: 'Yoga', back: 'Yoga — union of body and mind' },
  { front: 'Tư thế', back: 'Pose; posture (asana)' },
  { front: 'Luồng khí', back: 'Flow of energy; prana' },
  { front: 'Luân xa', back: 'Chakra — energy center' },
  { front: 'Hài hòa', back: 'Harmony; balance' },
  { front: 'Sức mạnh nội tâm', back: 'Inner strength' },
  { front: 'Sự kết nối', back: 'Connection (body-mind)' },
  { front: 'Cân bằng cơ thể và tâm trí', back: 'Balance of body and mind' },
  { front: 'Biến thể', back: 'Variation; modification (of a pose)' },
  { front: 'Nâng cao', back: 'Advanced; to advance' },

  // Common corrections
  { front: 'Đừng nín thở', back: 'Don\'t hold your breath' },
  { front: 'Thả vai xuống', back: 'Relax your shoulders down' },
  { front: 'Không gồng cổ', back: 'Don\'t tense your neck' },
  { front: 'Giữ hông vuông góc', back: 'Keep your hips square' },
  { front: 'Kéo rốn vào trong', back: 'Draw your navel in' },
  { front: 'Đặt bàn chân phẳng trên sàn', back: 'Place your foot flat on the floor' },
  { front: 'Cẩn thận đầu gối', back: 'Be careful with your knees' },
  { front: 'Đừng so sánh với người khác', back: 'Don\'t compare yourself to others' },
]
